### ISSUE TITLE
Location Toggle Button UI Error

### ISSUE THREAD

**Issue by Raiukage** [Total-RP/Total-RP-3#1094]
## Describe the issue
Bug Grabber/Bug Sack is flying off the rails because of some sort of error with this.

## Expected behaviour
Functionally, everything looks fine. I am able to click the button in the toolbar and it toggles as expected. But BugSack is insistent something is very, very wrong, to the point that it is bogging down the game.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest version] of the addon.
- [x] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
I just logged in with BugSack and Bug Grabber active.

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---
[TRP3.txt](https://github.com/user-attachments/files/16357109/TRP3.txt)

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Raenore** [comment]
Hello there!

TRP does not actually maintain the code for the TRP3 Location Toggle addon.

That is done by another dev. It might be best to contact them on [Curseforge](https://www.curseforge.com/wow/addons/trp3-location-toggle) or [Github](https://github.com/reed216/TRP3-Location-Toggle) to update it.

**Comment by Raiukage** [comment]
Awesome!

And it hasn't been updated since 10.2.0 if anyone else reports that here.

Thank you for the fast response and enjoy the pre-patch!
