### ISSUE TITLE
Custom Relations disappeared

### ISSUE THREAD

**Issue by Justb0gg** [Total-RP/Total-RP-3#1136]
## Describe the issue
I was making some custom relations to add to different characters I had met but while I was editing one of them it failed to save so I tried closing it and reloading the UI and now the customization panel on the left side of the TRP3 main window is gone and any profiles that had the custom relation I was trying to edit are completely blank on my character's directory and I can't even access the relations customization page to change it.

## Expected behaviour
The customization panel to be visible and usable again.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest version] of the addon.
- [x] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

**Comment by Solanya** [comment]
We have a suspicion on the issue at hand, but just to be sure, could you send the `totalRP3.lua` file in `World of Warcraft\_retail_\WTF\Account\**YOUR_ACCOUNT_NAME**\SavedVariables`? If it is the correct issue, I'll also be able to fix it until we release the new version to prevent it.
