### ISSUE TITLE
Images keep resetting and moving in TRP on their own

### ISSUE THREAD

**Issue by karmeshshadowaxe** [Total-RP/Total-RP-3#1148]
Every time I log out/login or reload my UI, the images in my TRP keep shifting. 

![image](https://github.com/user-attachments/assets/ab34a61e-6c73-434a-b474-f00a74fe5bc0)

For example, the moon in the background keeps shifting position on its own. It was centered perfectly and then upon logging back in, it moves to the left and uncenters itself. It also keeps resizing itself from 650x650 back down to 550x550 on its own. 

![image](https://github.com/user-attachments/assets/fb7a6c08-478f-4122-b99d-f17d83a7cc05)

After /reload-ing once more, the axe and shield insignia fades into the background. I didn't change anything.

![image](https://github.com/user-attachments/assets/608bc688-435f-4d55-9cf6-9ea6b0c4cff5)

Logging out and back in once more seems to fix it but it's completely random. 

Thank you for the amazing addon!

**Comment by Solanya** [comment]
Hey,

The overlapping images trick is a quirk of Blizzard's rendering and not something we support ourselves, which means any issue arising from it is not something we can or would do anything about at the moment.
