### ISSUE TITLE
Option to use a specific profile as the "default" profile for new characters

### ISSUE THREAD

**Issue by Ellypse** [Total-RP/Total-RP-3#122]
> **Verisimi on CurseForge:**
> Is there any way to turn off automatically making a profile every time I roll a character? I have a LOT of PvE alts on other servers that I don't need/want profiles for and it just makes it hard to find the profile I  DO want to switch to when there's such a huge list for characters I am never going to need a profile on. I'd rather have an 'opt in' to save a profile  when I roll characters. This is a great add on and I love it and you clearly put a lot of time and effort into it. Thanks for all you do, and no big deal if this isn't possible.

We would want a way for Total RP 3 to use only one profile by default, instead of creating new ones for each character. This option would be opt-in (to avoid confusion for new players switching characters) and would be reset if the profile is deleted.

**Comment by Connor-Macleod** [comment]
What if instead of making a single profile by default, we prevent profiles from showing up in the list until they've been changed away from containing nothing but the toon name/class?

**Comment by Ellypse** [comment]
I don't think hiding existing profile to users based on if they have valid content or not is a good idea. It can lead to confusion, you would see your new character using a profile that is not currently listed. Also, you will never be able to delete those profiles, so they will pile up silently.

Somewhere in the settings, we should have a dropdown to choose between creating a new profile or using a default one, something like:

```
New characters uses: [New profile        V]
					 [Ellypse-KirinTor    ]
					 [Marybell            ]
					 [Baa'l               ]
```

**Comment by Meorawr** [comment]
> Instead of profile tabs, you would see a single message indicating that you need to create a new profile to be able to edit it.

As long as this single message has a button or link right there on the page that'd allow users to perform that action, instead of saying "go to the X page and do Y". Optionally this could prompt for a profile name and, if so, should default to the current profile naming scheme ("character - server").
