### ISSUE TITLE
Add option to replace %t in chat messages by the target's RP name

### ISSUE THREAD

**Issue by Ellypse** [Total-RP/Total-RP-3#123]
It can be useful to use the `%t` annotation in a chat message to insert the target's name when it is too complicated to type. Total RP 3 should offer an option (I think enabled by default) to automatically replace `%t` by the target's RP name if the target is a known player with an RP profile.

**Comment by Meorawr** [comment]
I'll take a look at this for a future update (probably not 1.6.7, but we'll see). We'll use `%xt`/`%xf` to line up with XRP's implementation, since overriding the default tokens might cause interop issues with other addons.
