### ISSUE TITLE
Post BfA launch "Spring" cleaning

### ISSUE THREAD

**Issue by Ellypse** [Total-RP/Total-RP-3#158]
After the whole Battle for Azeroth rush calms down, this repository needs some good cleaning.

- [x] Remove old stuff in the Documents folder
- [x] Clean abandoned branches, move to [GitFlow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)
- [x] Improve continuous integration through Travis CI (use Lua check for every commit, stronger Luacheck rules, require a valid return from Travis CI for pull requests)
- [x] Either update or remove old tools (totalRP3_Localizator, totalRP3_zTest)

**Comment by Meorawr** [comment]
I believe we can close this now as all the tasks listed seem to have been completed.
