### ISSUE TITLE
Add option to only scan map for guildmates

### ISSUE THREAD

**Issue by Ellypse** [Total-RP/Total-RP-3#173]
From Curse:
>Arizosa [#1051](https://www.curseforge.com/wow/addons/total-rp-3?comment=1051)
>Hi =) I am wondering if there is a way that you can use the map feature to choose to only see your guildies, if they are IC, and not everyone that's IC in your zone if you do not want to see them at that time?

**Comment by Meorawr** [comment]
Didn't we do this in like 2.6.0?
