### ISSUE TITLE
Review roleplay experience values

### ISSUE THREAD

**Issue by Solanya** [Total-RP/Total-RP-3#178]
Currently, Experienced roleplayer is the default state for roleplay experience, which probably isn't reflecting the actual experience for players who don't pay attention to that dropdown.

There should be a default value (Either not set, or "normal" roleplayer), with New/Experienced/Volunteer being manually selected. Maybe add an icon for experienced ?

Additionally, this flag should be account-wide.

**Comment by Connor-Macleod** [comment]
Definitely agree with all points here.
I might even suggest having a popup suggesting you pick an option at first login. as currently it's missed by those who most need it (new roleplayers)

**Comment by Ellypse** [comment]
The popup on first login is planned see #179

**Comment by Raenore** [comment]
This should have been resolved in #927.
