### ISSUE TITLE
Current Issue with tooltips with Tiptac installed.

### ISSUE THREAD

**Issue by rozynrot** [Total-RP/Total-RP-3#182]
There seems to be an error with the interaction between TRP3 and Tiptac right now.   I have tried running TRP3 by itself and it works perfectly fine. When I load it + Tiptac, the information tooltip is just blank, sometimes with the icons arrayed around in odd areas. It's not throwing any errors that I can see, but it's obviously not intended to be like this. Included a screenshot showing the issue with both of them installed. Both of them are currently up to date for me.  Going back to the Tiptac version from 5 days ago fixes the issue as well

![image](https://user-images.githubusercontent.com/41770502/43302024-1e2ee300-911d-11e8-8b46-721ea75551cf.png)

**Comment by Ellypse** [comment]
This is an issue in TipTac's code. A fix has been provided to them, it's now up to them to release an update.

**Comment by Ellypse** [comment]
As TipTac is being slow at fixing this, we should start looking into bundling a temporary fix for TipTac.

**Comment by Ellypse** [comment]
**Development note:**
- The issue with bad usage of the LibMSP is one thing that will be fixed on TipTac's side.

- There is a second issue when Total RP 3 hides the default game tooltip that makes the text inside Total RP 3's tooltip not visible, as shown on the screenshot provided in this issue.

**Workaround:**

Disabling the option to hide the default tooltip will bring back Total RP 3's text.

**To do:**
- [ ] Implement a temporary workaround for the bad usage of LibMSP by TipTac. Make sure to check the version number of TipTac before implementing the workaround so we only hack LibMSP when necessary. 
- [ ] Fix the display issue in Total RP 3's tooltip when the default game tooltip is hidden by Total RP 3.

**Comment by Aerithissa** [comment]
Ellypse, thank you so much for the work around.  I've been going crazy without Tiptac.

So happy to be using both again =), the default tool tip is a small price to pay if it means the workaround works =)

**Comment by Seranth** [comment]
If you just change the "Anchored frame" in the TRP3 settings you to "TipTac" it'll show correctly again.
