### ISSUE TITLE
Potential nil indexing when saving first glances presets

### ISSUE THREAD

**Issue by Solanya** [Total-RP/Total-RP-3#274]
Reported on Discord, an issue might be happening when trying to save a preset, need to analyze if we can reproduce it.

> Message: ...s\totalRP3\modules\register\main\register_glance.lua:371: attempt to index local 'glanceTab' (a nil value)
> Time: Fri Feb 15 11:49:17 2019
> Count: 1
> Stack: ...s\totalRP3\modules\register\main\register_glance.lua:371: attempt to index local 'glanceTab' (a nil value)
> [C]: ?
> ...s\totalRP3\modules\register\main\register_glance.lua:371: in function <...s\totalRP3\modules\register\main\register_glance.lua:370>
> ...s\totalRP3\modules\register\main\register_glance.lua:552: in function <...s\totalRP3\modules\register\main\register_glance.lua:546>
> ...s\totalRP3\modules\register\main\register_glance.lua:606: in function <...s\totalRP3\modules\register\main\register_glance.lua:606>
> Interface\AddOns\totalRP3\core\impl\ui_tools.lua:169: in function func'
> ...3\libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua:1183: in functionMSA_DropDownMenuButton_OnClick'
> ...3\libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua:156: in function <...3\libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua:155>

**Comment by Meorawr** [comment]
Fixed in #339 (released in version 1.6.6).
