### ISSUE TITLE
[PTR 8.2] Replace music filepaths with file IDs

### ISSUE THREAD

**Issue by Solanya** [Total-RP/Total-RP-3#294]
Filepaths are getting removed for everything outside of the Interface folder, which means musics cannot be played using PlayMusic anymore. From testing in-game, while not knowing if it was always the case, PlaySound called on a music will stop the current music and restart it afterwards like PlayMusic does, so working with IDs won't be an technical issue.

We can use two databases to build a new music table : 
- soundkit.db2 can help us filter sound IDs based on the SoundType (musics having a type of 28).
- soundkitname.db2 can help us keep a list with names matching an ID.

I am currently unsure if it is worth sending the music name across protocols. In case someone has an older addon version without an updated list, I'm considering showing the ID instead of the name. This will have to be discussed to make sure TRP and MRP are on the same wavelength.

While this change will allow us to give access to files previously without filenames (like the Void Elf music), the work required to convert filepaths into fileIDs doesn't sound worthwhile, so music themes will have to be reassigned by players (It might be worth an extraordinary popup on login to warn players if they had a music theme in a profile).

**Comment by Meorawr** [comment]
Fixed in 1.6.1. YOU'RE WELCOME BY THE WAY.
