### ISSUE TITLE
Player names in world map tooltip are not following the increased color contrast setting

### ISSUE THREAD

**Issue by Ellypse** [Total-RP/Total-RP-3#298]
**Describe the bug**
Player names that are shown in tooltips when looking at player locations on the world map are not using the increased color contrast setting, like in other places.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have the option to dynamically increase color contrast on names enabled
2. Use the maps scan to show other TRP3 users on the map
3. Find a void elf with a dark purple name

**Expected behaviour**
The name of the edgy void elf should have been made ligther to be more readable on the dark tooltip background

**Version of the add-on:**
Total RP 3 1.6.0

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Comment by Meorawr** [comment]
Fixed in 1.6.1.
