### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by narcyssa406** [Total-RP/Total-RP-3#308]
Date: 2019-06-25 18:00:12
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\totalRP3\totalRP3.lua line 119:
   Error during TRP3 loading sequence: ...nterface\AddOns\totalRP3\modules\map\map_markers.lua line 33:
   Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: TRP3_ScanLoaderFrame:SetPoint.
Debug:
   (tail call): ?
   [C]: error()
   totalRP3\totalRP3.lua:119:
      totalRP3\totalRP3.lua:112
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:450: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:569: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1210:
      ..\FrameXML\UIParent.lua:1108
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AAPCore, v8.1056
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  AzerothAutoPilot, v
  BagBrother, v
  Bagnon, v8.1.9
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  EmoteSplitter, v1.5.8
  LootAppraiser, vv1.9.3
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  Tongues, v1.8.0
  totalRP3, v1.6.0
  totalRP3Data, v
  totalRP3Extended, v1.3.1
  totalRP3ExtendedImpExport, v1.3.1
  totalRP3ExtendedTools, v1.3.1
  TradeSkillMaster, vv4.7.8
  TRP3CurrentlyFrame, v1.7
  BlizRuntimeLib_enUS v8.2.0.80200 <none>
  (ck=396)

**Comment by narcyssa406** [comment]
I have updated, restarted the client, reinstalled TRP and continue to get this message. Thanks!

**Comment by Meorawr** [comment]
```
totalRP3, v1.6.0
```
Can you confirm what version you've updated to? Latest is 1.6.1.2.

**Comment by TrinitysEnd** [comment]
Current version is 1.6.1.3, Meorawr

**Comment by Meorawr** [comment]
GOD BLOODY ANNOUNCEMENTS CHANNEL

**Comment by narcyssa406** [comment]
1.6.1.3

**Comment by narcyssa406** [comment]
Date: 2019-06-25 18:26:45
ID: 5
Error occured in: Global
Count: 1
Message: ...nterface\AddOns\totalRP3\core\impl\configuration.lua line 80:
   Unknown config key: comm_broad_use
Debug:
   [C]: ?
   [C]: assert()
   ...nterface\AddOns\totalRP3\core\impl\configuration.lua:80:
      ...nterface\AddOns\totalRP3\core\impl\configuration.lua:79
   (tail call): ?
   ...alRP3\core\impl\communication_protocol_broadcast.lua:337: callback()
   ...ddOns\totalRP3\libs\Ellyb\Tools\EventsDispatcher.lua:74: TriggerEvent()
   ...face\AddOns\totalRP3\libs\Ellyb\Tools\GameEvents.lua:43:
      ...face\AddOns\totalRP3\libs\Ellyb\Tools\GameEvents.lua:41
Locals:

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AAPCore, v8.1056
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucScanData, v8.1.6229 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  AzerothAutoPilot, v
  BagBrother, v
  Bagnon, v8.1.9
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  EmoteSplitter, v1.5.8
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  Informant, v8.1.6246 (SwimmingSeadragon)
  LootAppraiser, vv1.9.3
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Stubby, v8.1.6240 (SwimmingSeadragon)
  Tongues, v1.8.0
  totalRP3, v1.6.0
  totalRP3Data, v
  totalRP3Extended, v1.3.1
  totalRP3ExtendedImpExport, v1.3.1
  totalRP3ExtendedTools, v1.3.1
  TradeSkillMaster, vv4.7.8
  TRP3CurrentlyFrame, v1.7
  BlizRuntimeLib_enUS v8.2.0.80200 <none>
  (ck=41a)

**Comment by Solanya** [comment]
Your latest error info still shows Total RP 3 version as 1.6.0. Latest version is 1.6.1.3. If you're using the Twitch app, make sure it's installing the addon in the right path : *Your WoW folder*/\_retail\_/Interface/AddOns
