### ISSUE TITLE
Can't load TRP

### ISSUE THREAD

**Issue by Cyngen80** [Total-RP/Total-RP-3#316]
Greetings I am having issues getting TRP 3 to work. I receive the following every time I log in.

TRP3_API.events.FireEvent::WorkFlow_on_Load
...interface\Addons\TotalRP3\modules\map\map markers.lua:3:Action[SetPoint]failed because[SetPoint would result in anchor family connection]: attempted from: TRP3_ScanLoaderFrame:SetPoint.

Note: If you just recently updated the addon remember that you need to fully relaunch the game client. Updating while the game client is open will not load new files.

I have done as suggested but still I keep getting the error message. What can I do to fix said issue? Thank you in advance for your assistance.

**Comment by Solanya** [comment]
Make sure that TRP3 is updated to the latest version (1.6.2). You should see the version number displayed above that error message.

**Comment by Cyngen80** [comment]
So when I log into the game it says 1.6.0. However, I have updated it to 1.6.2 through Twitch. However, it won't register the newer version.

**Comment by Solanya** [comment]
Make sure the path where the Twitch client is installing the addons is the right one : 
*Your WoW folder*/\_retail\_/Interface/AddOns

**Comment by Cyngen80** [comment]
lol....I have no idea why that was going to my PTR file. Thanks! I feel stupid. lol
