### ISSUE TITLE
Total RP 3 in Russian client breaks the declension system.

### ISSUE THREAD

**Issue by Natans8** [Total-RP/Total-RP-3#322]
In the Russian Language there is a form of grammatical declension. For example, "To Ivan" will be "Иван**у**" and "With Ivan" will be "С Иван**ом**". In the Russian WoW client, when you create a character, you choose the different declension forms, to be used in quests, dialogues and emotes. But with Total RP 3, the whole system breaks apart, including non-rp players and NPCs. When you or any other player uses a standard in-game emote (like /hello of /sorry), the name of the target appears gray and with a bracket before it, and with the wrong (mostly automatically chosen) declension. If the target is a roleplayer, the emote shows his in-game name instead of the character name.

I don't expect to include this actually very complicated grammatical instrument in the add-on's functionality, but at least to fix this issue in targets without the add-on and keep the original colors of the target's nickname with other roleplayers.

![image](https://user-images.githubusercontent.com/52584161/60747909-61b77c80-9f91-11e9-994a-f1befc134ba4.png)
In the first emote, I am using a /hello emote on another roleplayer, his character name is "Cтигма Предвестница Злобы", his in-game name is "Мелуда" and his character color is dark purple. As you can see, when I used the emote on him, his name is gray, with an unnecessary bracket and not the character name.
In the second emote, the same player is using the same emote on a NPC, the name also appears in the same way.
Here is the same emotes without Total RP 3 for reference.
![image](https://user-images.githubusercontent.com/52584161/60748057-c58e7500-9f92-11e9-8701-c519b41fda68.png)

Total RP 3 1.6.2 (and every version before it)

The issue appeared in every TRP3 version in combination with every add-on.

The same issue observed with all my friends with the Russian client.

**Comment by Solanya** [comment]
I can't promise anything, working with Unicode is pretty obnoxious in Lua and we don't have the means to test properly on our clients. In chat settings (Настройки чата) you should have an option to Use OOC detection (Использовать обнаружение "вне отыгрыша"), disabling this setting should stop the behaviour at least.

**Comment by Natans8** [comment]
It took some time but finally we see it fixed! Thank you from all of the Russian rp community!

**Comment by Solanya** [comment]
You're welcome! Beta was the only time I could get a hand on the Russian localized client, so I knew it was the time to look into the issue :)
