### ISSUE TITLE
Please align the version scheme of TRP3 with SemVer (e.g. TRP3 1.7.0+ is somehow tagged as 1.7.0 Alpha 2)

### ISSUE THREAD

**Issue by andrewpong** [Total-RP/Total-RP-3#332]
**Is your feature request related to a problem? Please describe.**
Not a problem per se... but the fact that this addon has a SemVer-like version scheme that doesn't adhere to SemVer's principles is confusing. I had a friend state that they were still running alpha TRP3 code, which made me assume they were using some ancient build of TRP... but after doing some research, I find out version 1.7.0 Alpha 2 is the latest release.

[Jackie Chan Meme](https://www.tvovermind.com/wp-content/uploads/2018/04/37c1b462d20d40f3c9c030986b69f6c02a66fae9b5f1b9871cb71daecf26e625.jpg)

**Describe the solution you'd like**
Fix the versioning so that it adheres to SemVer, or just make up your own versioning scheme to prevent confusion.

**Describe alternatives you've considered**
I've considered not submitting this Feature Request.

**Additional context**
Nope. This Feature Request should be pretty self explanatory.

**Comment by TrinitysEnd** [comment]
TRP3 1.7.0 is tagged as alpha because of the way WoW Addon sites register releases that are not public releases but early versions of it, usually referred to as test builds. These exist so that multiple people can take them for a test run and see if anything breaks horribly (or even not so horribly). Twitch refers to these as Beta and Alpha. Alpha 2 means it is in stage two of testing.

If you are looking for the latest Public release, it is 1.6.3.1. There is no mislabeling going on. Just that you are looking at a test build.

**Comment by Solanya** [comment]
1.7.0-alpha2 is an alpha version of the upcoming 1.7.0 version which is still in development.
Alpha builds are hidden from Curseforge's regular files view (unless you specifically go to View All), won't be downloaded by the Twitch app (unless you specifically set it to accept alpha builds for this addon) and are not advertised anywhere but our Discord server with explicit mention that it is a test version.

I did however notice that we are packaging test builds on WoWInterface as well, which should not happen. We'll look into preventing the script from uploading test versions to WoWInterface in the future.

**Comment by Ellypse** [comment]
I'll suggest being less condescending and memeing in future tickets if you want to be taken more seriously.

"or just make up your own versioning scheme to prevent confusion"
What if our current versioning scheme already is something we came up with and isn't SemVer, and the confusion comes from you trying to apply SemVer to it despite the fact that it's not advertised to be SemVer anywhere?

**Comment by andrewpong** [comment]
Sorry, Ellypse.
