### ISSUE TITLE
NPC talk bug with NPC name in Brackets

### ISSUE THREAD

**Issue by SleepyDremora** [Total-RP/Total-RP-3#333]
This happens to me since 8.2 release. Every time when i use Brackets on the Pet name, so it had color, i either don't see my messages, but other people can see it, or i see this error.
For time being i could just use 1.6.1 version of TRP3 but now even on 1.6.1 i see that error

Message: ...face\AddOns\totalRP3\modules\chatframe\chatframe.lua:460: attempt to call global 'configIncreaseNameColorContrast' (a nil value)
Time: Sun Jul 28 18:59:52 2019
Count: 4
Stack: ...face\AddOns\totalRP3\modules\chatframe\chatframe.lua:460: attempt to call global 'configIncreaseNameColorContrast' (a nil value)
...face\AddOns\totalRP3\modules\chatframe\chatframe.lua:460: in function <...face\AddOns\totalRP3\modules\chatframe\chatframe.lua:408>
...face\AddOns\totalRP3\modules\chatframe\chatframe.lua:503: in function <...face\AddOns\totalRP3\modules\chatframe\chatframe.lua:487>
...face\AddOns\totalRP3\modules\chatframe\chatframe.lua:554: in function `filterFunc'
Interface\AddOns\Prat-3.0\services\chatsections.lua:50: in function <Interface\AddOns\Prat-3.0\services\chatsections.lua:43>
Interface\AddOns\Prat-3.0\services\chatsections.lua:320: in function `SplitChatMessage'
Interface\AddOns\Prat-3.0\addon\addon.lua:590: in function <Interface\AddOns\Prat-3.0\addon\addon.lua:565>
(tail call): ?
Interface\FrameXML\ChatFrame.lua:3005: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: name = "Shiersia"
senderID = "Dâedra-ArgentDawn"
chatColor = <table> {
 class = <table> {
 }
}
nameColor = nil
petProfile = <table> {
 profileName = "Shiersia"
 PE = <table> {
 }
 data = <table> {
 }
 links = <table> {
 }
}
innerName = "Shiersia"
customColor = <table> {
 class = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to call global 'configIncreaseNameColorContrast' (a nil value)"
disabledByOOC = <function> defined @Interface\AddOns\totalRP3\modules\chatframe\chatframe.lua:76
getConfigValue = <function> defined @Interface\AddOns\totalRP3\core\impl\configuration.lua:79
CONFIG_NPCSPEECH_REPLACEMENT = "chat_npcspeech_replacement"
Globals = <table> {
 addon_name_me = "TRP3: Extended"
 player_icon = "Ability_Racial_EntropicEmbrace"
 clients = <table> {
 }
 player_class_loc = "Warlock"
 player_race_loc = "Void Elf"
 addon_name = "Total RP 3"
 player_character = <table> {
 }
 player_faction_loc = "Alliance"
 is_trial_account = 0
 PSYCHO_MAX_VALUE_V1 = 6
 DEBUG_MODE = false
 required_trp3_build = 66
 icons = <table> {
 }
 player = "Dâedra"
 version = 72
 addon_name_short = "TRP3"
 PSYCHO_DEFAULT_VALUE_V2 = 10
 player_id = "Dâedra-ArgentDawn"
 PSYCHO_DEFAULT_RIGHT_COLOR = <table> {
 }
 RELATIONS = <table> {
 }
 PSYCHO_DEFAULT_VALUE_V1 = 3
 build = <function> defined @Interface\AddOns\totalRP3\core\impl\globals.lua:129
 RELATIONS_ORDER = <table> {
 }
 player_hash = 4028887006
 addon = <table> {
 }
 extended_version = 1017
 extended_display_version = "1.3.3"
 version_display = "1.6.3.1"
 player_realm = "Argent Dawn"
 player_realm_id = "ArgentDawn"
 player_class_index = 9
 PSYCHO_MAX_VALUE_V2 = 20
 empty = <table> {
 }
 addon_name_extended = "TRP3: Extended"
 PSYCHO_DEFAULT_LEFT_COLOR = <table> {
 }
 addon_id_length = 15
}
TRP3_API = <table> {
 inventory = <table> {
 }
 utils = <table> {
 }
 MapDataProvider = <table> {
 }
 CompanionProfileChatLinksModule = <table> {
 }
 MapScannersManager = <table> {
 }
 Locale = <table> {
 }
 currently_frame = <table> {
 }
 ChatLinks = <table> {
 }
 map = <table> {
 }
 Ellyb = <table> {
 }
 r = <table> {
 }
 slash = <table> {
 }
 VERSION_DISPLAY = "1.6.3.1"
 importer = <table> {
 }
 ProfilesChatLinkModule = <table> {
 }
 profile = <table> {
 }
 popup = <table> {
 }
 Events = <table> {
 }
 BUILD_NUMBER = 798
 AtFirstGlanceChatLinksModule = <table> {
 }
 ADVANCED_SETTINGS_DEFAULT_VALUES = <table> {
 }
 ChatLinkModule = <table> {
 }
 RegisterPlayerChatLinksModule = <table> {
 }
 module = <table> {
 }
 RegisterCompanionChatLinksModule = <table> {
 }
 extended = <table> {
 }
 register = <table> {
 }
 ADVANCED_SETTINGS_STRUCTURE = <table> {
 }
 ChatLinkTooltipLines = <table> {
 }
 target = <table> {
 }
 chat = <table> {
 }
 flyway = <table> {
 }
 toolbar = <table> {
 }
 security = <table> {
 }
 globals = <table> {
 }
 dashboard = <table> {
 }
 getSafeValueFromTab

**Comment by Solanya** [comment]
Thanks for the report, will fix for next version.

**Comment by SleepyDremora** [comment]
Thanks!
