### ISSUE TITLE
Quest items usage blocked while TRP is enabled

### ISSUE THREAD

**Issue by Falconartist** [Total-RP/Total-RP-3#335]
Started encountering an issue with opening default Blizzard windows during combat (most often, clicking on a quest from my objectives list to view it fully on the map or bringing up the group finder), where it would report an error into the chatbox: "Interface action failed because of an AddOn", and refuse to ever open until I've left combat and try to open them again.

I don't run a very complex UI, just a couple of lightweight addons: Bagnon and Shadowed Unit Frames, occasionally with HandyNotes. But after disabling all of them one by one, I've narrowed it down to only happening when TRP is enabled, even by itself with no other addons to conflict with.

Another issue that might be related, but I haven't been able to reliably test is having someone whisper me while I'm in combat. I have it set to add a new tab to my chat window when someone whispers me, and if I try to close that tab before I've left combat, it causes my chat box to glitch out by never getting rid of the whisper text, so even once I've gone back to my normal chat tab, whatever the person whispered pops back up by clipping over the normal text- not as a new undocked chat window that can be moved around, only the text. After a minute or two, the whisper tab itself comes back (with no new whispers, just to be clear) as if I've never closed it, and the only way to fix it is by leaving combat and THEN closing it. I don't get any notice about an addon failure like the other issue, but since they both seem to involve combat, I'm pretty sure that they're related.

I've been using TRP for years, and this issue has only popped up since patch 8.2 when I updated TRP to version 1.6.3 through the Twitch client. I've already tried doing a full UI wipe and re-importing all of my profiles from scratch, but it hasn't helped.

**Comment by Solanya** [comment]
Blizzard added some UI lockdown in combat in 8.2 which seems to be causing issues, we're looking into them but reproducing them is tricky.
