### ISSUE TITLE
Can't see my profile tooltip (Trp3-Classic)

### ISSUE THREAD

**Issue by Cienne** [Total-RP/Total-RP-3#347]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

1. Hover over character frame

**Expected behaviour**
 Instead of getting my profile tooltip in the lower right corner, I get information about party options. 

**Screenshots or error message**

![Screenshot (187)](https://user-images.githubusercontent.com/54727823/64055344-b7974380-cb40-11e9-81d1-a91807e18baa.png)

**Version of the add-on:**
Total RP 3: Classic 1.13.2

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Additional context**

**Comment by Meorawr** [comment]
Can you run the following command in the chat frame: `/run SetCVar("showNewbieTips", "0")`

You may get prompted to enable dangerous scripts, if so accept it and re-run it.

**Comment by Solanya** [comment]
This is not a bug but rather due to the behaviour of a setting, just disable "Show Detailed Tooltips" in the Display category of the Interface Options.

![image](https://user-images.githubusercontent.com/17127080/64055373-454c5080-cb8c-11e9-9fdd-0603fa211904.png)

**Comment by Cienne** [comment]
> This is not a bug but rather due to the behaviour of a setting, just disable "Show Detailed Tooltips" in the Display category of the Interface Options.

Oh, thank you very much! I tried going through my settings but couldn't find it.
