### ISSUE TITLE
Unable to download TRP3: Classic using Twitch

### ISSUE THREAD

**Issue by skultulla** [Total-RP/Total-RP-3#353]
**Describe the bug**
I click on Install using the Twitch app, which works just fine for retail TRP3, and twitch opens but nothing happens. I'm not redirected to the installer within the twitch app. Also, I can't find TRP3: Classic anywhere under the 'Get More Addons' tab, I can only see the regulat TRP3.

**Version of the add-on:**
Total RP 3: Classic

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
N/A

**Comment by Solanya** [comment]
Make sure to select the Classic folder in the dropdown in the top left corner when managing/looking for addons to be able to install addons on Classic.

![image](https://user-images.githubusercontent.com/17127080/64132276-ef1b1f80-cdce-11e9-89d4-7bd1cc9f796f.png)
