### ISSUE TITLE
[Classic] Companion profile cannot be set on "non combat pets"

### ISSUE THREAD

**Issue by whisperity** [Total-RP/Total-RP-3#370]
**Describe the bug**
A companion profile cannot be set for a non-combat pet (summoned from cages/eggs/etc.) in **Classic.**

**To Reproduce**
Steps to reproduce the behaviour:
1. Summon a pet, like [this cute thing](https://classic.wowhead.com/npc=9662/sprite-darter-hatchling)
2. Create a companion profile
3. Click the **`Binds`** button.
4. Click *Target*.
5. Error saying "Target is not a valid pet, mage elemental, minion, renamed battle pet" pops up and nothing happens.

**Expected behaviour**
Be able to set a story and fluff text for the companion.

**Screenshots or error message**
![image](https://user-images.githubusercontent.com/1969470/67632212-06432e80-f8a1-11e9-8df1-37117f88bc32.png)

**Version of the add-on:**
Total RP 3 1.6.7.1 (build 79) **Classic WoW version**

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes

**Comment by Solanya** [comment]
We are aware, Classic doesn't handle companions and mounts the same way as Retail does.
We are in the process of building a system to handle them in Classic.
