### ISSUE TITLE
[Suggestion][Classic] Increase Text Field for 'Additional Information'

### ISSUE THREAD

**Issue by illutian** [Total-RP/Total-RP-3#379]
I would suggest giving the 'Additional Information' section the ability to either word-wrap or to have at least two lines per text box.

Right now, I'm noticing that Mottoes and Physiognomy tend to have text that, at times, requires me to expand TRP3's main window to nearly the entire width of a game window (1920x1080). Just to read the whole entry.

**Comment by Meorawr** [comment]
Our current plan is to make it so that those fields show long inputs in a tooltip on-hover; we'd rather not encourage long inputs via multiline fields on the characteristics page since wordy descriptions are generally best suited for the About tab.
