### ISSUE TITLE
Can't see other peoples profiles 

### ISSUE THREAD

**Issue by authorbaby** [Total-RP/Total-RP-3#382]
**Describe the bug**
Hello there! I don't know if this is a bug or not, but I saw something on your main page about not being able to see other people's profiles from other servers however I have seen and been able to interact with people from Moonguard and other servers before who have your addon (I am on Azgalor) I can see my friend's profile because they are the same realm (Azgalor) but I cannot see my other friend's profile (Moonguard) anymore or other people who are from Moonguard when we join their shard and I can no longer scan the map for RPers, I just thought it was pretty cool I was able to see other people's profiles and interact even though I am not on a RP server. Maybe you guys changed something recently? 

**Expected behaviour**
I expected to see their tooltip frames pop up and I'd be able to click open their profile like I use to and or be able to see their profiles pop up via scanning the map but the map can no longer scan.  

**Screenshots or error message**
N/A

**Version of the add-on:**
Current, 1.6.9. 

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes however I did disable it, nothing happened. 

**Additional context**
N/A

**If your issue is related to profile data, please provide your data file.**
N/A

**Comment by Solanya** [comment]
You cannot request cross-realm profiles unless you are Battle.net friend or in a group with the player, although you might see some of the profiles stored in your register if you got their profile while being on their server (but you won't see any modification they make afterwards); and you cannot scan the map for players on another realm. Neither is a bug, it is the normal behaviour.
