### ISSUE TITLE
Character like companion profiles

### ISSUE THREAD

**Issue by Hvedrun** [Total-RP/Total-RP-3#388]
**Is your feature request related to a problem? Please describe.**
I've got an Etheral Soul-Trader companion pet. This is a human sized humanoid, with humanesque intelligence. When creating a profile for this companion, it feels weird being forced to treat it as a pet. There are many fields I wish I could add for this companion, to make it appear as a person in its own right. Birth place, residence, family members, class, personality traits, a page with description and history, the same stuff as a character gets.

**Describe the solution you'd like**
An option to create profiles for companions that have all the same features as character profiles.

**Describe alternatives you've considered**
Written a restricted profile, and utilized the "At first glance" buttons.

**Additional context**
N/A

**Comment by Solanya** [comment]
Sorry I forgot to reply to you before. Currently this isn't something we are looking to do. It is a lot of work required for a very specific use case, as most pets & mounts would still fall in the current category. Such information can still be manually written in the description part of the pet instead.
