### ISSUE TITLE
Z-peral and Total RP3 bug

### ISSUE THREAD

**Issue by Kalerea** [Total-RP/Total-RP-3#390]
Just a little bug I wanted to share. If you use Z-peral and Total RP3 you can't see glares. The whole glare bar is gone and just wanted to ask if that is something that is gonna be fixed or is that to little of a bug to matter? Would just be nice to use both at the same time :P

**Comment by Ellypse** [comment]
Hello.

The glances bar should be attached to Total RP 3's own target frame, not the target's unit frame. As such, unit frames addons should not cause issues. If you changed the settings you can use the reset button to reset the position of the glance bar to be back on Total RP 3's target frame.

![ByJYCsww6v](https://user-images.githubusercontent.com/9035119/80734212-23d2a880-8b0f-11ea-84e0-9568abdd4232.jpg)
