### ISSUE TITLE
No description of "/trp3 stash" in "/trp3" help menu.

### ISSUE THREAD

**Issue by catthou** [Total-RP/Total-RP-3#391]
**Describe the bug**
When typing "/trp3" to get the help text for all trp commands, there's no text describing what "/trp3 stash" does.

**To Reproduce**
1. Type /trp3 in the chat box and hit enter.

Total RP 3 1.6.10

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Additional context**
Thankfully the stash command provides a warning before allowing the user to run it, but it'd be better to simply tell the user what it does before trying to invoke it.

**Comment by Solanya** [comment]
Hi, thanks for the report. Given that this is a debug command, we will remove it from the command help list next version to avoid confusion.
