### ISSUE TITLE
Unable to update addon

### ISSUE THREAD

**Issue by killersheep23** [Total-RP/Total-RP-3#395]
In the twitch addon page I'm unable to update TRP3 classic despite my version being out of date compared to my friends' versions which are 1.6.10 but I'm stuck on 1.6.8

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to twitch app
2. Click on mods
3. Scroll down to TRP3 classic 
4. See error - no update button available for the addon

**Expected behaviour**
A purple update button should appear but it doesn't 

**Screenshots or error message**
![Screenshot (133)](https://user-images.githubusercontent.com/64622011/80773842-0d4e4080-8b53-11ea-972a-dd59e15a3f22.png)

> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://mods.curse.com/addons/wow/BugSack) add-on.

**Version of the add-on:**
Total RP 3 1.6.8

**Comment by Meorawr** [comment]
Twitch client issues are generally outside of our domain but here's a few things you could try:

[This link](https://www.curseforge.com/wow/addons/total-rp-3-classic/download/2899066?client=y) *might* cause the Twitch client to pop up and download the latest version by force. It might also do absolutely nothing as it just did for me.

Alternatively you can perform the manual installation steps outlined in the [installation guide](https://github.com/Total-RP/Total-RP-3/wiki/How-to-install-and-update-Total-RP-3#manually) to update the addon.
