### ISSUE TITLE
[Classic][Error] Possible TRP3 LUA Error with "Chatframe" and Prat

### ISSUE THREAD

**Issue by illutian** [Total-RP/Total-RP-3#436]
Keep getting this error every time I log in after updating all the addons that, for what ever reason, updated their Classic versions.

I've tried rolling back...still get it. It goes away if I disable Prat. But like I said. I rolled back (both addons) and it still gives me the error.

I even tried downloading the latest Classic versions of both addons manually (in case Twitch App went retarded again).

Date: 2020-10-14 18:59:07
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\totalRP3\modules\chatframe\prat.lua line 81:
   attempt to call field 'GUIDIsPlayer' (a nil value)
Debug:
   (tail call): ?
   totalRP3\modules\chatframe\prat.lua:81: ?()
   ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   Prat-3.0\addon\addon.lua:698:
      Prat-3.0\addon\addon.lua:613
   (tail call): ?
   ..\FrameXML\ChatFrame.lua:2797:
      ..\FrameXML\ChatFrame.lua:2790
   (tail call): ?
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
None
AddOns:

**Comment by speedwaystar** [comment]
a temporary fix is

if not message.GUID or not C_PlayerInfo.GUIDIsPlayer or not C_PlayerInfo.GUIDIsPlayer(message.GUID) then return end;

i think the C_PlayerInfo namespace is Retail only.

**Comment by cowrecked** [comment]
I, too, get the following error:

Date: 2020-10-15 12:39:55
ID: 1
Error occured in: Global
Count: 6
Message: ..\AddOns\totalRP3\modules\chatframe\prat.lua line 81:
   attempt to call field 'GUIDIsPlayer' (a nil value)
Debug:
   totalRP3\modules\chatframe\prat.lua:81: ?()
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   Prat-3.0\addon\addon.lua:698:
      Prat-3.0\addon\addon.lua:613
   (tail call): ?
   ..\FrameXML\ChatFrame.lua:2797: ChatFrame_OnEvent()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
None
AddOns:

**Comment by Meorawr** [comment]
This should be fixed in version 2.0.2, which we released some number of hours ago.
