### ISSUE TITLE
Profile Creation Issues

### ISSUE THREAD

**Issue by Shatterhail** [Total-RP/Total-RP-3#452]
**Describe the bug**
Long story short, whenever I try and create a new profile for a pet and/or companion, or even try and add character traits below the basic info such as age, race, etc, I get half a second worth of lag and nothing happens. I've tried mass-deleting everything TRP related and reinstalling newer versions several times but nothing seems to work regardless.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'About'
2. Click on 'Add Trait'

**Expected behaviour**
After restoring everything, the expected result would be to be able to produce pet or mount profiles again. Still no result.

**Screenshots or error message**
> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://www.curseforge.com/wow/addons/bugsack) add-on.

**Version of the add-on:**
Total RP 3 2.3.0

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

**Additional context**

**If your issue is related to profile data, please provide your data file.**

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/_retail_/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net; replace `_retail_` with `_classic_` if you are using Total RP 3: Classic). You can just drag and drop it here, no need for a third party service.

**Comment by Solanya** [comment]
> **Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No

Try that first, outdated addons using one of the libraries we use (like CrossRP) cause that issue.

**Comment by Shatterhail** [comment]
Did it to no avail. Not to worry though, clearing back-up files and re-installing the game twice fixed it. Thanks for the assist though!
