### ISSUE TITLE
Not seeing my roleplay name in the chat windows.

### ISSUE THREAD

**Issue by roshanmatthews** [Total-RP/Total-RP-3#454]
**Describe the bug**
I added a roleplaying first and last name in my characters profile, however I'm only seeing my profile name in the chat windows...not other players with trp3 roleplay names as well. I remember I used to see everyone who had the trp3 addon with their custom name in the chat windows.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots or error message**
> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://www.curseforge.com/wow/addons/bugsack) add-on.

**Version of the add-on:**
Total RP 3 1.4.4

**Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?**
Yes/No

**Additional context**

**If your issue is related to profile data, please provide your data file.**

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/_retail_/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net; replace `_retail_` with `_classic_` if you are using Total RP 3: Classic). You can just drag and drop it here, no need for a third party service.

**Comment by Solanya** [comment]
> Version of the add-on:
Total RP 3 1.4.4

Current version is 2.0.3

**Comment by Solanya** [comment]
Nevermind, reopening because that's just the template not being filled properly, but if you have not gotten their profiles before by mousing over them, their roleplay name isn't known to you so it can't appear.

**Comment by roshanmatthews** [comment]
I used to see other people's roleplay names in the chat windows...general chat, whispers, says, guild...now I only see my roleplay name when I type in text

**Comment by roshanmatthews** [comment]
Sorry for to update the ticket this is happening on version 2.0.3

**Comment by Solanya** [comment]
Can you check that you have their profiles in the directory on the TRP main window?

**Comment by roshanmatthews** [comment]
I have lots of people listed the directory list.  What am I supposed to do here?

**Comment by Solanya** [comment]
Check that you have the profiles of the people in chat in the directory.
