### ISSUE TITLE
TRP 3 is Bugged

### ISSUE THREAD

**Issue by ShimeSham** [Total-RP/Total-RP-3#457]
So for a long time now, i have not been able to click any of the buttons that got bars and such, like the tap of if i am a widow or single. The front page of t trp where you can show if you are a new rp person or viteran is also bugged and cannot be clicked on.

https://user-images.githubusercontent.com/73508524/97247312-b1156200-17ff-11eb-8e2e-a3ddf54420be.PNG

My trp should be up to date, can't find any updates and u have tried to uninstall and install it again. 

Just tried to see if it works if all my addons off but it, it worked.
So now i tried taking one off each time to see if it works and it seems like its the RCLootCouncil it is not working with.

**Comment by Solanya** [comment]
RCLootCouncil is not yet updated for 9.0 (although there are beta versions currently available on Curseforge) and should be disabled until it is.
