### ISSUE TITLE
Total RP3 module in Prat issue

### ISSUE THREAD

**Issue by Bohwuen** [Total-RP/Total-RP-3#463]
I have the Prat addon, and the rp names are not shown, when I recose the prat configuration and look for the Total RP3 module I get the following error:

Message: Interface \ AddOns \ Prat-3.0 \ addon \ locales.lua: 69: Locale key module_desc is not provided.
Time: Tue Nov 17 14:35:44 2020
Count: 3
Stack: Interface \ AddOns \ Prat-3.0 \ addon \ locales.lua: 69: Locale key module_desc is not provided.
[string "= [C]"]: in function `error '
[string "@Interface \ AddOns \ Prat-3.0 \ addon \ locales.lua"]: 69: in function <Interface \ AddOns \ Prat-3.0 \ addon \ locales.lua: 67>
[string "@Interface \ AddOns \ Prat-3.0 \ addon \ modules.lua"]: 256: in function `GetDescription '
[string "@Interface \ AddOns \ Prat-3.0 \ addon \ options.lua"]: 555: in function `member '
[string "@Interface \ AddOns \ Prat-3.0_Libraries \ AceConfig-3.0 \ AceConfigDialog-3.0 \ AceConfigDialog-3.0.lua"]: 221: in function <... nfig-3.0 \ AceConfigDialog-3.0 \ AceConfigDialog-3.0.lua : 169>
[string "@Interface \ AddOns \ Prat-3.0_Libraries \ AceConfig-3.0 \ AceConfigDialog-3.0 \ AceConfigDialog-3.0.lua"]: 512: in function <... nfig-3.0 \ AceConfigDialog-3.0 \ AceConfigDialog-3.0.lua : 501>
[string "= [C]"]:?
[string "@Interface \ AddOns \ Prat-3.0_Libraries \ AceGUI-3.0 \ AceGUI-3.0.lua"]: 72: in function <... \ AddOns \ Prat-3.0_Libraries \ AceGUI-3.0 \ AceGUI-3.0.lua : 70>
[string "@Interface \ AddOns \ Prat-3.0_Libraries \ AceGUI-3.0 \ AceGUI-3.0.lua"]: 306: in function `Fire '
[string "@Interface \ AddOns \ Prat-3.0_Libraries \ AceGUI-3.0 \ widgets \ AceGUIWidget-DropDown.lua"]: 362: in function <... braries \ AceGUI-3.0 \ widgets \ AceGUIWidget-DropDown.lua: 360 >

Locals: <none>

**Comment by Solanya** [comment]
Thanks for the report, seems like an easy issue to fix so it should be bundled with the version coming later today.

**Comment by Bohwuen** [comment]
Although the update of the Total RP3 module for Prat worked, it seems that there is another problem that again ignores the RP name in the chat window for the [Say] channel, however for the [emote] channel it works perfectly

![imagen](https://user-images.githubusercontent.com/62218802/99655954-992aaa00-2a5c-11eb-979e-57d6a4000da1.png)

**Comment by Solanya** [comment]
Can you check that the Say channel is checked in the TRP chat settings?

**Comment by Bohwuen** [comment]
It has been strange it was in Short title + name + surname, I have changed it to name + surname and it worked, I changed it back to a Short title + name + surname and it was solved with the desired result

![imagen](https://user-images.githubusercontent.com/62218802/99657598-a8125c00-2a5e-11eb-8d5f-9ff8a890a33e.png)

**Comment by Solanya** [comment]
And if you /reload, does it keep working? If not, it's possible Prat is registering something after us that we have to take into account.

**Comment by Bohwuen** [comment]
following your last instructions I have reloaded and it has happened again, but now I know what I must do to make it work

![imagen](https://user-images.githubusercontent.com/62218802/99658245-82398700-2a5f-11eb-9e05-5bfabf9c1f98.png)

**Comment by Solanya** [comment]
Hmmm, will try to look into what order modules are loaded in to fix it.

**Comment by Bohwuen** [comment]
Now even if I change the aforementioned it does not work again
