### ISSUE TITLE
Rumour Tab next to the 'About' Tab

### ISSUE THREAD

**Issue by HellaRoyal** [Total-RP/Total-RP-3#467]
I think it would be nice to have a seperate tab for rumors, maybe split into three seperate text windows for common rumors, rare rumors and rumors that can only be used with the player's permission!

**Comment by Meorawr** [comment]
Heya, bit of a delayed response. While the idea is cool and I definitely see some people using rumours in some capacity we're not planning on implementing this at the current time.

If we were to add a custom glances field the first roadblock we'd hit is UI space. At the minute our profile editor is rather full and adding additional stuff increases the complexity of the UI for newer users, and can make some people generally feel that such fields _need_ to be filled out in some way. While I've seen people use rumours from time to time I can't personally say that I've ever seen them used enough to justify the cost of implementing them.

An additional point of concern would be support with other addons, such as MRP. We work closely with the authors of other RP addons and, generally, new field proposals are agreed upon as a group and support implemented across the board. We don't feel there'd be much support for a dedicated "rumours" field at this time, and typically we've tried to avoid implementing TRP-exclusive fields for some time now.

Adding additional input fields for profiles is generally only done if we feel that no existing field suitably fits, and in most cases we prefer that people use the free-form nature of the additional info, about, or glance sections where possible. Our feeling is that rumours are a perfect example of a freeform input that is best suited by the existing Glances or About features on profiles. Glances have the advantage of showing in an easily visible place on most RP addons, and the About section of course lets you be more creative with how your profile is laid out - rumours and all. One thing you could do with the About section is to swap to "template 2" which allows the creation of framed sections of the profile and, in there, create a section dedicated to rumours.
