### ISSUE TITLE
Target of target battle pet error

### ISSUE THREAD

**Issue by Tiiara** [Total-RP/Total-RP-3#469]
Happened in old dalaran, in a raid group. 
One of our members was targeting a neutral squirrel by the well in front of the Ledgermain Lounge. 
When I hovered over the "target of target" interface, meaning the squirrel, this error showed up. 

Message: Interface\AddOns\totalRP3\core\impl\ui_tools.lua:510: Usage: UnitBattlePet("unit")
Time: Wed Nov 18 22:05:59 2020
Count: 3
Stack: Interface\AddOns\totalRP3\core\impl\ui_tools.lua:510: Usage: UnitBattlePet("unit")
[string "=[C]"]: ?
[string "@Interface\AddOns\totalRP3\core\impl\ui_tools.lua"]:510: in function <Interface\AddOns\totalRP3\core\impl\ui_tools.lua:507>
[string "@Interface\AddOns\totalRP3\modules\register\main\register_tooltip.lua"]:358: in function <...\totalRP3\modules\register\main\register_tooltip.lua:357>
[string "@Interface\AddOns\totalRP3\modules\register\main\register_tooltip.lua"]:1165: in function <...\totalRP3\modules\register\main\register_tooltip.lua:1162>
[string "=[C]"]: in function `SetUnit'
[string "@Interface\AddOns\PitBull4\UnitFrame.lua"]:256: in function <Interface\AddOns\PitBull4\UnitFrame.lua:251>

Locals: (*temporary) = nil

**Comment by Solanya** [comment]
Fix is already in the pipes for next version

**Comment by Meorawr** [comment]
Should be fixed in the now-released v2.1.1.
