### ISSUE TITLE
LUA Issue when loading into Wow?

### ISSUE THREAD

**Issue by queenbii** [Total-RP/Total-RP-3#471]
## Describe the issue
The addon isn't loading in when I load into WoW, even if it is the only addon I'm loading. 

## Expected behaviour
I expect to be able to use the addon.

## Issue checklist

> You can place an "x" inside the brackets for each option below to tick it.

- [x ] Retail
- [ ] Classic

Please confirm that you are running the latest version of the addon. 

> You can check the installed version of the addon by opening the "Addons" window in-game from the character selection screen or game menu and checking the version number shown in the tooltip of the "Total RP 3" entry in the list.

> The latest version of the addon can be found on CurseForge for [Retail](http://curse.totalrp.com/) and [Classic](http://classic.totalrp.com/) game versions.

- [x ] I am running the latest version of the addon as listed on the CurseForge project page.

Please confirm whether or not the issue occurs only with Total RP 3 enabled.

- [x ] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list)

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

## Additional files
Please attach any additional applicable files such as screenshots, error logs, or profile data files. Files can be dragged and dropped into this report to attach them for upload.

> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://www.curseforge.com/wow/addons/bugsack) addon.

> Profile data is stored in the `totalRP3.lua` file located in your [SavedVariables](https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables) folder.

- [x ] I have attached screenshot(s) of the issue.
- [ ] I have attached an error report of the issue.
- [ ] I have attached my profile data file to reproduce the issue.

![image](https://user-images.githubusercontent.com/74807528/99868197-f1a99680-2b85-11eb-9458-6867acd8d5df.png)

**Comment by TrinitysEnd** [comment]
You are not running the most up to date version of the Addon. The current latest is version 2.1.1 which fixes the errors you have. The most up to date version is found [here](https://www.curseforge.com/wow/addons/total-rp-3). Or use your addon manager of choice to download it instead.

**Comment by queenbii** [comment]
![image](https://user-images.githubusercontent.com/74807528/99868441-21599e00-2b88-11eb-9c8e-2d1a734cc0d3.png)

I just used force update for the third time, and it is still giving me the same issue. I'm not sure if the "updated" files are going somewhere else maybe? It was doing this when I was using Twitch earlier, and now that I have Ajour as well.

**Comment by TrinitysEnd** [comment]
I don't know Ajour that well, but ensure that the install location is [Beginning path]\World of Warcraft\_retail_\Interface\AddOns. If it's going anywhere else, then that'd be causing your issue.

**Comment by queenbii** [comment]
I'll double check my file routes with both Ajour and Twitch. Thank you for your help!
