### ISSUE TITLE
"Hide immediately instead of fading" non-functional.

### ISSUE THREAD

**Issue by uberphailure** [Total-RP/Total-RP-3#472]
## Describe the issue
The option "Hide immediately instead of fading" in TRP3 > Settings > Tooltip settings doesn't work any longer after updating to the most recent version (2.1.1).

## Expected behaviour
When you mouse over a character/portrait, a brief tooltip will pop up over your cursor saying their name, titles, 'currently', etc.. By default, if you move your cursor away from their character/portrait, it follows your cursor and lingers a second before fading away slowly. This option in the menu is supposed to cause that tooltip to immediately disappear instead of fading. It worked a few days ago and now it's not working.

## Issue checklist

- [ X ] Retail
- [ X ] I am running the latest version of the addon as listed on the CurseForge project page.
- [ X ] The issue occurs with Total RP 3 as the only enabled addon.

## Steps to reproduce

1. Left-click on the TRP3 map button
2. Click on 'Settings
3. Click on 'Tooltip settings'
4. Scroll down to "Hide immediately instead of fading" under 'Common settings'
5. While checked, it does not function as intended.

**Comment by TrinitysEnd** [comment]
This is currently disabled right now while the TRP team investigates a bug involving it. It appears this wasn't added to the Curseforge changelog but was noted on the TRP discord. 
![November22_2255_2577](https://user-images.githubusercontent.com/37823216/99935606-e4231680-2d15-11eb-8dab-c59029c0fc3d.png)

**Comment by uberphailure** [comment]
> 
> 
> This is currently disabled right now while the TRP team investigates a bug involving it. It appears this wasn't added to the Curseforge changelog but was noted on the TRP discord.
> ![November22_2255_2577](https://user-images.githubusercontent.com/37823216/99935606-e4231680-2d15-11eb-8dab-c59029c0fc3d.png)

Oh pardon me! I was debating on whether I should join the discord or post here and I made the wrong decision haha. Thanks for the reply.
