### ISSUE TITLE
Chat Settings Error: Posts won't appear in chatbox

### ISSUE THREAD

**Issue by yepnix** [Total-RP/Total-RP-3#473]
## Describe the issue
Whenever someone whose name would be formatted by TRP3 make a post, an error appears and the post does not show up in the chat window. Disabling the used chat channel causes the error to not show up and the post to appear normally, albeit without the formatting. I am running the Macintosh WoW client, if that is relevant.

## Expected behaviour
I expect the post to appear in the chat window with the custom options from Chat Settings applied to that chat channel.

## Issue checklist
Select the game version(s) that this issue occurs on.

> You can place an "x" inside the brackets for each option below to tick it.

- [X] Retail
- [ ] Classic

Please confirm that you are running the latest version of the addon.

> You can check the installed version of the addon by opening the "Addons" window in-game from the character selection screen or game menu and checking the version number shown in the tooltip of the "Total RP 3" entry in the list.

> The latest version of the addon can be found on CurseForge for [Retail](http://curse.totalrp.com/) and [Classic](http://classic.totalrp.com/) game versions.

- [X] I am running the latest version of the addon as listed on the CurseForge project page.

Please confirm whether or not the issue occurs only with Total RP 3 enabled.

- [X] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list)

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

1. Load latest version of WoW on Mac with latest version of TRP3 as the only add-on.
2. Attempt to type in Say (for instance).
3. See error (attached below); chat post does not appear in window.
4. Open TRP3 Main Window.
5. Go to Settings > Chat settings
6. Disable Say in Used Chat Channels
7. Attempt to type in Say again.
8. Receive no error; chat post appears in window.

## Additional files
Please attach any additional applicable files such as screenshots, error logs, or profile data files. Files can be dragged and dropped into this report to attach them for upload.

> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://www.curseforge.com/wow/addons/bugsack) addon.

> Profile data is stored in the `totalRP3.lua` file located in your [SavedVariables](https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables) folder.

- [ ] I have attached screenshot(s) of the issue.
- [X] I have attached an error report of the issue.
- [ ] I have attached my profile data file to reproduce the issue.

[TRP3 Chat Settings Error- Posts won't appear in chat box.txt](https://github.com/Total-RP/Total-RP-3/files/5603660/TRP3.Chat.Settings.Error-.Posts.won.t.appear.in.chat.box.txt)

**Comment by Meorawr** [comment]
This should be fixed in 2.3.
