### ISSUE TITLE
TRP still shows to other players when disabled in addons

### ISSUE THREAD

**Issue by Keaning** [Total-RP/Total-RP-3#474]
## Describe the issue
When disabling the addon in the addons menu, other users can still see my TRP profile.

## Expected behaviour
The Addon to cease functioning.

## Issue checklist
totalRP3-2.1.1

> You can place an "x" inside the brackets for each option below to tick it.

- [x ] Retail
- [ ] Classic

Please confirm that you are running the latest version of the addon.

> You can check the installed version of the addon by opening the "Addons" window in-game from the character selection screen or game menu and checking the version number shown in the tooltip of the "Total RP 3" entry in the list.

> The latest version of the addon can be found on CurseForge for [Retail](http://curse.totalrp.com/) and [Classic](http://classic.totalrp.com/) game versions.

- [x ] I am running the latest version of the addon as listed on the CurseForge project page.

Please confirm whether or not the issue occurs only with Total RP 3 enabled.

- [x ] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list)

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

1. Go to Game Menu
2. Click on Addons
3. Scroll down to TRP 3
4. Disabling the addon does not prevent other users seeing the TRP profile

## Additional files
Please attach any additional applicable files such as screenshots, error logs, or profile data files. Files can be dragged and dropped into this report to attach them for upload.

> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://www.curseforge.com/wow/addons/bugsack) addon.

> Profile data is stored in the `totalRP3.lua` file located in your [SavedVariables](https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables) folder.

- [x] I have attached screenshot(s) of the issue.
- [ ] I have attached an error report of the issue.
- [ ] I have attached my profile data file to reproduce the issue.

![WoWScrnShot_113020_113504](https://user-images.githubusercontent.com/75252090/100605740-48d70600-3300-11eb-90c1-d81b36735243.jpg)

**Comment by Solanya** [comment]
It's intended behaviour.
Players see the profile you had because it's still stored in their profile directory. They have no way to know you disabled the addon. The profile usually disappears from their directory automatically after about 10 days not receiving your profile again.
