### ISSUE TITLE
Choosing the word between the guild rank and the guild

### ISSUE THREAD

**Issue by Minaeem** [Total-RP/Total-RP-3#491]
**Is your feature request related to a problem? Please describe.**
If a guild is named "Champs dorés" and my rank is "marchand" it appears as "marchand _de_ Champs dorés" which makes no sense.

**Describe the solution you'd like**
Could you add a box like for the name and eyes color, but for the word between the guild rank and the guild name ?

**Describe alternatives you've considered**
Or a dropdown list of word or group of words we could use like "de, de la, du, des, etc..."

**Comment by Solanya** [comment]
Hey. A few reasons why we're not looking to do this:
- We're supporting a few languages and this would require to look up grammar details for all of them.
- The selected format would then have to be sent over comms, which while not taking a lot of bandwidth, is still only for a minor aesthetic detail.
- This doesn't work across languages.
