### ISSUE TITLE
Additional pet support

### ISSUE THREAD

**Issue by Ellypse** [Total-RP/Total-RP-3#52]
>BrotherNero, comment #700
>Greetings. I play an Unholy Death Knight and we have a talent called "All Will Serve" which summons a skeleton that follows us around and shoots arrows at people we don't like.  Blizzard has named this guardian "Risen Skulker" when his proper name should be "Bob". When I try to assign a profile to him, it does not allow me to do so. When you get a chance, could you please fix this, if it is at all possible? Thanks for your time.

**Comment by Ellypse** [comment]
Also check Hati for hunters.

**Comment by Meorawr** [comment]
Implemented in 2.2.
