### ISSUE TITLE
KUI Nameplates "Tank Mode" colours being overwritten

### ISSUE THREAD

**Issue by Xideta** [Total-RP/Total-RP-3#527]
## Describe the issue
Since the 2.3 update, tanking mode (KUI Nameplates Core -> Threat -> Enable Tank Mode)  on KUI nameplates is being overwritten by TRP, making the nameplate colour briefly flicker to the having aggro colour (default green) before being recoloured (and locked) to the creatures hostility colour. This happens no matter what options I untick in the nameplate settings, but doesn't happen if I disable the new KUI module.

## Expected behaviour
The nameplate colour change of tank mode shouldn't be overwritten by TRP, as this didn't happen with the old module.

## Issue checklist
Please select any applicable options from the below list.

- [x] The issue occurs with the [latest Retail version] of the addon.
- [ ] The issue occurs with the [latest Classic version] of the addon.
- [ ] The issue occurs with Total RP 3 as the only enabled addon.
- [X] The issue occurs only with other addon(s) enabled (please provide a list).

List: 
Kui Media
Kui Nameplates: Core Config
Kui Nameplates
Kui Nameplates: Core

(Default Kui nameplates installtion)

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

1. Spec tank
2. Taunt overworld mob (Not a dummy)
3. Don't kill it
4. See nameplate flicker and change colour every few seconds.

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest Retail version]: https://www.curseforge.com/wow/addons/total-rp-3/files
[latest Classic version]: https://www.curseforge.com/wow/addons/total-rp-3-classic/files

**Comment by Meorawr** [comment]
Should have this fixed in 2.3.2, sorry about that.

**Comment by Meorawr** [comment]
Fixed in the released-I-think-yesterday-I'm-not-sure-the-days-have-blended-together 2.3.2 release.
