### ISSUE TITLE
Blizzard Nameplates issue TRP3

### ISSUE THREAD

**Issue by yuutayo** [Total-RP/Total-RP-3#542]
## Describe the issue
The new Blizzard nameplates function with version 2.3.2 doesn't work when importing trp profiles that were backed up. The totalRP3.lua file specifically seems to be what contains the "trp3_nameplates (version 1)" dependency, as well as all TRP3 profile info. When I delete that file and run the game, TRP3 loads perfectly, and the nameplates function, but as soon as I try to import my profiles it stops working, and the Modules Status tab in Settings reads that there are missing dependencies. I'm obviously not a proficient at coding (or educated), but I spent a solid 2 1/2 hours figuring out which file was doing this.

## Expected behaviour
I expected to be able to see the chosen RP names + titles displayed with health bars above other players, and myself in game.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest Retail version] of the addon.
- [ ] The issue occurs with the [latest Classic version] of the addon.
- [x] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest Retail version]: https://www.curseforge.com/wow/addons/total-rp-3/files
[latest Classic version]: https://www.curseforge.com/wow/addons/total-rp-3-classic/files

**Comment by Meorawr** [comment]
Would you be able to attach a copy of the problematic `totalRP3.lua` file in question? I'll need it to try and figure out what's going on.

With the bad file loaded does the "Nameplates" section in the left sidebar show at all?

![image](https://user-images.githubusercontent.com/287102/113729059-8ef90780-96ee-11eb-88b9-cc75f0cfbe7c.png)

**Comment by yuutayo** [comment]
> Would you be able to attach a copy of the problematic `totalRP3.lua` file in question? I'll need it to try and figure out what's going on.
> 
> With the bad file loaded does the "Nameplates" section in the left sidebar show at all?
> 
> ![image](https://user-images.githubusercontent.com/287102/113729059-8ef90780-96ee-11eb-88b9-cc75f0cfbe7c.png)

I tried, but the site doesn't support the file type. I can grab a mediafire link rq if that would be helpful?

The nameplates section doesn't show up at all with the file loaded, and there is no option to enable the function in the modules tab. 

![Wow_c2yAXx6gFR](https://user-images.githubusercontent.com/82014923/113797642-83193f80-9706-11eb-87ae-c3296b190408.png)
![Wow_dW30shqGb8](https://user-images.githubusercontent.com/82014923/113797655-89a7b700-9706-11eb-8ebf-d0736a44e17e.png)

**Comment by Solanya** [comment]
Looks like you have the module "Nameplates" disabled, which is the missing dependency.

**Comment by yuutayo** [comment]
The issue actually ended up being with my WoW client interface settings. I completely missed the nameplates module, sorry about that, but even with it enabled I still wasn't seeing anyone's custom names. I did have "Always show nameplates" unchecked, however, and checking it ended up fixing the issue. Thanks for the help!
