### ISSUE TITLE
Total RP shortening URL links in chat,

### ISSUE THREAD

**Issue by myhrazayn** [Total-RP/Total-RP-3#559]
Hello! I have recently updated TRP today, and noticed that whatever link I send in chat, or sent by others in chat would be shortened. Notably, the URL must follow a set format of 

http(s)://125.com/567

I have not encountered this issue before the update, attached is also a screenshot which demonstrates it, I typed a link in say and the chat would be converted to an uninteractable short line of code. Disabling the addon will cause links to revert to normal behaviour, which could mean that the addon is causing it.
![Untitledss](https://user-images.githubusercontent.com/83533912/116807613-b6fd4e80-ab66-11eb-8b68-03fac4299a57.png)

**Comment by Meorawr** [comment]
It's a known issue that'll be fixed in version 2.3.4. There's a beta release available on which resolves the issue; you can grab it through the CurseForge client by setting the Release Type of the addon to "Beta".

![image](https://i.imgur.com/t0LPZPb.png)
