### ISSUE TITLE
Cannot install? Does not appear in World of Warcraft.

### ISSUE THREAD

**Issue by RVexer** [Total-RP/Total-RP-3#574]
## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest Retail version] of the addon.
- [ ] The issue occurs with the [latest Classic version] of the addon.
- [ ] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce

1. Go to 'World of Warcraft'
2. Click on 'Addons'
3. Scroll down to 'Other TotalRp3 Addons'

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.
![Where is it](https://user-images.githubusercontent.com/84253880/118381428-f9338080-b5a7-11eb-98e0-cf55a7b9a3c9.PNG)
[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest Retail version]: https://www.curseforge.com/wow/addons/total-rp-3/files
[latest Classic version]: https://www.curseforge.com/wow/addons/total-rp-3-classic/files

**Comment by Solanya** [comment]
You're likely doing something wrong when installing. If you're installing manually, you should have the two folders totalRP3 and totalRP3_Data from the .zip file placed in Interface/AddOns.
As a reminder, we have a guide on how to install the addon in the wiki section: https://github.com/Total-RP/Total-RP-3/wiki/How-to-install-and-update-Total-RP-3
