### ISSUE TITLE
Nameplates are no longer working due to missing depdency?

### ISSUE THREAD

**Issue by thepuppeh** [Total-RP/Total-RP-3#580]
## Describe the issue
For some reason my nameplates which used to work just fine, showing up above people's chars with title, name, last name etc etc.. now it no longer works? it just shows the character name and in the modules page it says -trp3_nameplates(version 1) is missing? I have not downloaded or even changed the mod to cause such?

## Expected behaviour
The nameplates should show as they had before again.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x ] The issue occurs with the [latest Retail version] of the addon.
- [ ] The issue occurs with the [latest Classic version] of the addon.
- [ x] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
No clue? Just happened
![unknown](https://user-images.githubusercontent.com/85793675/121777335-c920d280-cb91-11eb-8a15-af809be1e06f.png)

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest Retail version]: https://www.curseforge.com/wow/addons/total-rp-3/files
[latest Classic version]: https://www.curseforge.com/wow/addons/total-rp-3-classic/files

**Comment by Solanya** [comment]
You need to enable the basic "Nameplates" module as well.

**Comment by Meorawr** [comment]
![image](https://user-images.githubusercontent.com/287102/121777391-aee2f680-cb89-11eb-9506-2538e4cdb55f.png)

For reference, it's further down in the list. There'll be some work in the future that cleans this up to make it less of a trap.

**Comment by thepuppeh** [comment]
oh wow that worked.. I have no idea why it was off.. Guess I am just retarded.. Well thanks a lot! That fixed it.
