### ISSUE TITLE
Sidebar that won't disappear? Not sure if bug

### ISSUE THREAD

**Issue by sylvanpriince** [Total-RP/Total-RP-3#584]
For some reason, I have this sidebar here that I can't get rid of. I'm not sure if it's from the Extended addon, but it's only on my main toon that this appears on.
Here's an image of what that sidebar looks like:
![image](https://user-images.githubusercontent.com/87071369/124748308-ef1b6780-def0-11eb-85d1-9cfe6639cd38.png)
It gets in the way of one of my other addons, and frankly, it's kind of annoying! I don't know how to get rid of it, either.

Does anyone know how to get rid of this thing?

**Comment by Solanya** [comment]
You currently have a campaign active in TRP3: Extended which involves using an action. Pause the campaign in the Quest Log section of TRP3 and the bar will be hidden.
