### ISSUE TITLE
trp custom names wont show

### ISSUE THREAD

**Issue by edgeman1512** [Total-RP/Total-RP-3#586]
## Describe the issue
Give us a clear and concise description of what the issue is.
the kui nameplates with the custom names won't show it only shows the standard blizzard name for the character i can still see the custom name if I hover over them though while it isn't game-breaking it is certainly annoying

## Expected behaviour
Give us a clear and concise description of what you expected to happen.
the name to be there

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [ x] The issue occurs with the [latest version] of the addon.
- [x ] The issue occurs with Total RP 3 as the only enabled addon.
- [x ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.
their are no steps it just happens 

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Solanya** [comment]
Sounds like either you disabled friendly nameplates (the shortcut to reenable them by default is Shift-V) or you're in an instance where customization can't be applied.
If it's neither, a screenshot of the issue would help.
