### ISSUE TITLE
KUI nameplates wont show

### ISSUE THREAD

**Issue by edgeman1512** [Total-RP/Total-RP-3#587]
## Describe the issue
Give us a clear and concise description of what the issue is.
KUI nameplates wont load
## Expected behaviour
Give us a clear and concise description of what you expected to happen.
i expected it to work
## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [ ] The issue occurs with the [latest version] of the addon.
- [ ] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Solanya** [comment]
There's not a lot of information provided so I'll have to take guesses.
- Make sure both the Nameplates and Kui Nameplates modules are enabled in TRP Settings > Modules status
- Make sure you have friendly nameplates enabled (Shift-V by default) and the "Always show nameplates" setting enabled in the game settings (Interface > Names)
- RP names cannot be displayed in instances, Blizzard locks them down.
