### ISSUE TITLE
Attempt to call field 'init' - Nil value

### ISSUE THREAD

**Issue by kimcheeseontoast** [Total-RP/Total-RP-3#589]
First error encountered with TRP3, I'm not sure how to explain it, it just won't load the button by the map nor can I see other TRP profiles or access my own to edit. I get the following; 

Error during addon loading sequence: 
Sequence ID: Globals.addon:OnEnable 
Sub-sequence ID: TRP3_API.popup.init
Error message; Interface\AddOns\totalRP3\totalRP3.lua:101: attempt to call field 'init' (a nil value)

I have no idea what this all means except there's something possibly interjecting with the Lua file called init. 

Usually on log in there wouldn't be much to miss but I noticed the icon was missing and no profiles came up when I hovered over toons in the city. - It just won't launch with all other addons disabled, I updated it, didn't work. I removed and reinstalled the addon, still nothing. (And yes I did follow the note, I always close the client when updating addons)

## Issue checklist

- [X] The issue occurs with the [latest version] of the addon.
- [X] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

![trp3_addon_screenshot_23082021](https://user-images.githubusercontent.com/89413690/130495099-d25d9d9f-1d2c-412f-b6b1-3953e212ad26.png)

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Meorawr** [comment]
2.3.2 is out of date and not compatible with the latest version of the game. Update the addon and it'll work again.
