### ISSUE TITLE
I can't see the TRP profiles of people from other servers

### ISSUE THREAD

**Issue by Taurenwarrior** [Total-RP/Total-RP-3#602]
## Describe the issue
Give us a clear and concise description of what the issue is.
The addond does not pick up other people who use the addon if their from another server unless I'm invited to their group and they can't see mine in return. I don't know if it's supposed to be that you can only see the profiles of those in your server or group but I don't like it. Especially considering I play in a server with a very low population.
## Expected behaviour
Give us a clear and concise description of what you expected to happen.
I expect to be able to see the profiles of other people from other servers.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [ x] The issue occurs with the [latest version] of the addon.
- [ ] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Solanya** [comment]
I'm sure you don't like it, but that restriction is on Blizzard, we cannot do anything about it. Your only alternative is adding players as B.net friends to see their profiles without being in a group.
