### ISSUE TITLE
Date formats

### ISSUE THREAD

**Issue by Solanya** [Total-RP/Total-RP-3#613]
All dates in both TRP3 and Extended use the "D/M/Y" format, but a setting could be provided to choose a different format (namely M/D/Y or Y/M/D which seem to be the only two common alternative formats).

In TRP3, this is only relevant for the profile directory and easily replaceable (just a DATE_FORMAT to swap).

**Comment by kisiseldwarf** [comment]
Hey ! I could maybe help on this, if you don't bother ? I look forward to contribute to some wow addon projects and this issue seems like a good first issue !

**Comment by Solanya** [comment]
Hi, sure 👍
Feel free to make a pull request once you want it reviewed/merged 😄 (and don't hesitate if you have any questions).

**Comment by kisiseldwarf** [comment]
I've made some changes, but I don't really know how to test it ! Is there a standard way to do so / do you have some tools ?
I've seen there's a dist recipe in the makefile (but I'm on windows currently so I don't know how to run it)

**Comment by Solanya** [comment]
Just copying the totalRP3 and totalRP3_Data folders in the usual addons folder and run it in-game.
You'll have to run `make libs` in the root folder containing those two folders first (For Windows 11: Shift-click in the root folder > Open Linux shell here)

**Comment by Meorawr** [comment]
Alternatively you can copy the contents of the Libs directory from a recent packaged release of the addon, if that's an easier route.

**Comment by Meorawr** [comment]
we did it
