### ISSUE TITLE
Custom Word/Name highlighter for chat

### ISSUE THREAD

**Issue by TheArchitect01** [Total-RP/Total-RP-3#615]
When having a lot of text/emote input from other players via chat, it is sometimes hard to keep track on when someone approaches you unless you see them face upfront.

Adding a custom word filter which does react on custom words (i.e. your characters name) to highlight it when a player is using said word via /say or an emote or /e. Maybe even add an optional simple sound cue that points out someone used the word. Also having the option to give it a custom color could help a lot.

I don't know of any alternate Addon or anything that does that.

**Comment by Solanya** [comment]
This is a feature that is more fit to be solved by using a chat addon.

Prat for instance has this feature integrated.
https://www.curseforge.com/wow/addons/prat-3-0
> Configurable alerts when your name or other word is mentioned
There might be others, that's just the first one I know of.
