### ISSUE TITLE
Color picker not working on Wrath

### ISSUE THREAD

**Issue by Solanya** [Total-RP/Total-RP-3#632]
Blizzard decided to remove RUNES from PowerBarColor (for whatever reason), so it was removed from Ellyb
https://github.com/Total-RP/Total-RP-3/blob/main/totalRP3/libs/Ellyb/Tools/ColorsManager.lua#L178
Unfortunately, we manually list the colors to display in the color picker in their respective categories, which in turn caused the color picker to not work on Classic.
https://github.com/Total-RP/Total-RP-3/blob/main/totalRP3/core/impl/popup.lua#L846

We can either manually add the color in the ColorManager, remove it from the color picker in Classic, or add checks to make sure missing colors don't entirely break the color picker. 🤔

**Comment by Meorawr** [comment]
I think we fixed this didn't we?
