### ISSUE TITLE
Wrath - Cannot assign companion profile to mage elemental.

### ISSUE THREAD

**Issue by Luridel** [Total-RP/Total-RP-3#634]
In Classic Wrath prepatch, I cannot give my water elemental a companion profile.

Binds -> Bound to -> Target gives me the result of "Your target is not a valid pet, minion, ghoul, mage elemental or a renamed battle pet."

Worth noting that I am using the Glyph of Eternal Water which removes one of my water elemental's abilities - it may count as a different creature in the API.

Running version 2.3.13.

**Comment by Meorawr** [comment]
We'll get this fixed in the next update; Water Elementals seem to be a bit weird on Classic Wrath.
