### ISSUE TITLE
Can't see friend's profiles on specific realm only

### ISSUE THREAD

**Issue by Heroic-Ryan** [Total-RP/Total-RP-3#636]
My friend and I play on two realms on WoW. Wyrmrest Accord and Moon Guard. On Moon Guard, I can see her profiles just fine, but on Wyrmrest Accord, her profiles just don't show up. I don't even get a blank profile. It's just nothing, as if TRP isn't installed.

It's not cross realm either. She and I are both on Wyrmrest Accord characters when this occurs.

The thing is, she has TRP installed and enabled, as do I. Not sure what the problem is.

The screenshot below is all I see when mousing over her. Names have been painted over for privacy's sake.
![InkedWoWScrnShot_101322_100923](https://user-images.githubusercontent.com/51721536/195635723-7729b07c-8421-4410-89a2-7253b9839a74.jpg)

**Comment by Ghostamoose** [comment]
Is this still occurring?
