### ISSUE TITLE
TRP3 Crashing

### ISSUE THREAD

**Issue by B0neCh3wer** [Total-RP/Total-RP-3#646]
## Describe the issue
After updating World of Warcraft to 10.0, and updating all my addons, I found that all functioned as normal except for TRP3, which gave me an error message. The addon would show up in my addons list, but would not come up under options. I tried using an older version of TRP3, but the problem still persisted. I've reinstalled, I've restarted, I've even turned my PC on and off again, yet the issue still remains.

## Expected behaviour
I expected the addon to run, I guess? I don't know, I don't have any experience with coding or anything... I just wanna RP :/
## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest version] of the addon.
- [x] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

I just launched the game after updating both the game and addon

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.
![Screenshot from 2022-10-26 16-19-27](https://user-images.githubusercontent.com/116746125/198076307-f1cba435-6de2-4f6d-9aa5-d96b9893e472.png)

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Meorawr** [comment]
You're not running the latest version - the chat output says version "2.3.12" but the latest is 2.4.0. Did you use an updater client like Wowup by any chance?

**Comment by B0neCh3wer** [comment]
No, I've installed the addon directly from Curseforge and dragged and dropped the files directly into my WoW files myself. I've deleted the old TRP3 files and reinstalled in as if brand new, but the issue still persists.

**Comment by Der-Systemfehler** [comment]
Delete the Cache Folder and all Total RP folders in your Interface -> Addons again. Unzip the TotalRP 2.4 again and reload

I had the exact same problem, that fixed it for me. Probably just the cache was the problem.

**Comment by B0neCh3wer** [comment]
Omg thank you, this fixed the issue, thank you so much!

**Comment by Der-Systemfehler** [comment]
No Problem! :)
