### ISSUE TITLE
Can't see/attach Companion profile to warlock Demon

### ISSUE THREAD

**Issue by SleepyDremora** [Total-RP/Total-RP-3#647]
## Describe the issue
Today after the Prepatch I can't see or Attach profile of my Shivarra or any other Demon,

## Expected behaviour
TRP says that profile is attached to demon, yet when I hover my cursor over it, nothing shows up, like I look at NPC/Player without profile in TRP3

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [X] The issue occurs with the [latest version] of the addon.
- [X] The issue occurs with Total RP 3 as the only enabled addon.
- [X] The issue occurs only with other addon(s) enabled (please provide a list).
TRP3, Extended, LUI3, KUI media, Battleground targets.

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

2. Click on 'Demon of a warlock.'

## Additional files
I can see my profile or profiles of other players, yet demon profile is broken,
![image](https://user-images.githubusercontent.com/53404600/198095748-dae9a1c5-13ad-402e-9350-693feccee87f.png)
![image](https://user-images.githubusercontent.com/53404600/198095792-e5d1e6cc-4c86-47cc-bdd0-6bf32608719b.png)

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Meorawr** [comment]
Issue was traced to colorblind mode on Discord and resolved in #649 (and #647 implicitly).
