### ISSUE TITLE
There is no longer an option in the right click context menu, either on the friends list or on a targeted character, to open their TRP profile.

### ISSUE THREAD

**Issue by Github-Sic** [Total-RP/Total-RP-3#654]
There is no longer an option in the right click context menu, either on character portrait or in friends list, to open a TRP profile.

**Comment by Ghostamoose** [comment]
This was [removed temporarily](https://github.com/Total-RP/Total-RP-3/blob/main/CHANGELOG.md#removed) due to a conflict with edit mode. Will be re-added when the conflict can be resolved.
