### ISSUE TITLE
Only I can see my water elemental's profile.

### ISSUE THREAD

**Issue by Luridel** [Total-RP/Total-RP-3#655]
As of version 2.4, I can now make a profile for my water elemental (thank you!) ... except nobody can see the profile except for the character who owns the elemental. Using Glyph of Eternal Water if this makes any difference. Playing on Classic Wrath.

**Comment by Solanya** [comment]
Other players would also need the new version to be able to see your pet profile. Can you confirm even people with 2.4 aren't able to see the elemental profile?

**Comment by Luridel** [comment]
Yes, I can confirm that my fully updated friends cannot see it, as well as myself while dual-boxing.

**Comment by Luridel** [comment]
Really appreciate you all trying to fix this. It still isn't actually fixed. Once again, fully updated, I can see the profile on my mage; second me while dual-boxing cannot see it.

The creature ID might be different in my case because my mage is using the Glyph of Eternal Water, which changes the elemental to make it persistent/removes one of its abilities.

**Comment by Meorawr** [comment]
I took an educated guess at the creature IDs since the test realms have been down for a while; could you run the following ingame after targeting your elemental and paste a screenshot here?

```
/dump UnitGUID("target")
```

**Comment by Luridel** [comment]
![image](https://user-images.githubusercontent.com/51339758/202833722-f9ce5d6f-25ad-4e49-91d3-88ae1c0b869d.png)

Done! This is on Wrath Classic, I do not have a mage on retail.

**Comment by Meorawr** [comment]
This should be fixed for real this time with 2.4.2. I also fully expect that by closing this ticket we'll discover that it's somehow _not_ fixed, but I'm willing to take that chance :)
