### ISSUE TITLE
Total RP 3 Randomly Assigning Keybinds

### ISSUE THREAD

**Issue by Github-Sic** [Total-RP/Total-RP-3#656]
This bug doesn't seem to be triggered by anything in particular. Since the patch, every so often every one of my number bar keys will present a Blizzard UI conflict with Total RP 3 until I force a UI reload. Running the latest version of TRP. My bindings in the addon are clear.

## Issue checklist

- [x ] The issue occurs with the [latest version] of the addon.
- [x ] The issue occurs with Total RP 3 as the only enabled addon.

## Steps to reproduce
Hard to reproduce! It's very unpredictable, unfortunately.

**Comment by Solanya** [comment]
Hey,

I'm confused by the report, are you saying the addon is setting keybinds on some of your buttons? I don't quite understand.

**Comment by Github-Sic** [comment]
> 

My wording was a bit confusing! It's throwing up conflicts in such a way that when I push keys 1 to =, it's attempting to trigger some function in TRP. Clicking skill icons isn't triggering the behaviour, so I'd have no clue what could be causing it to do this.

**Comment by Solanya** [comment]
So just the regular "Action blocked" message, it's not actually trying to trigger a function in TRP.
Can you send your totalRP3.lua file in `_retail_\WTF\Account\<your account>\SavedVariables`?

**Comment by Github-Sic** [comment]
[totalRP3.zip](https://github.com/Total-RP/Total-RP-3/files/9899896/totalRP3.zip)
Sure thing. Put it in a Zip file so I could straight upload it.
