### ISSUE TITLE
Copy and Paste Icons and Colors from the "Additional Information" and "Personality Traits" Sections

### ISSUE THREAD

**Issue by Ghostamoose** [Total-RP/Total-RP-3#659]
A number of people I know have profiles that they duplicate when making new characters, some of these profiles can contain a LOT of "additional information" and "personality traits" entries. 

![image](https://user-images.githubusercontent.com/10636803/200055027-b537016e-1cbd-48fd-aba3-6c94d9051f36.png)

With this many entries, it becomes very tedious to manually search for, and set the icon for each one, the same going for the personality traits, but with the added steps of altering the colors for each side.

This issue is vaguely mentioned in #532, but figured I'd expand a little bit here in case this is an area that you guys feel is worth exploring. A (relatively) simple (ish) way of alleviating this would be allowing players to select an icon in one tab, then copy it with a modifier + click on the currently chosen icon slot, and use a different modifier to paste it into the other icon slots.

For example, pick an icon for slot 1, alt + click to copy it, then shift + click on the other icon selectors to paste the icon into those slots.

For colors on personality traits, this is less of an issue as you can save color presets fairly easily, but if the copy + paste functionality can be reused, it would be a nice-to-have.

I'd be happy to look into this if it's something y'all think would be a good fit.

**Comment by Meorawr** [comment]
I'd say don't work on it; I'd rather blow up that entire section of the UI from scratch rather than have you waste effort on something I'll delete and redo.

Hidden modifiers aren't something I'd really want, since no one'll know about them and I doubt people are editing their profiles enough to remember that mod1+click is copy and mod2+click is paste, and not the other way around.
