### ISSUE TITLE
Dracthyr use DEFAULT_ICON_NAME instead of an appropriate icon

### ISSUE THREAD

**Issue by TheAmariaSilverbird** [Total-RP/Total-RP-3#667]
## Describe the issue
The default interface icon for male and female dracthyr use the DEFAULT_ICON_NAME (the question mark icon).

## Expected behaviour
The default interface icon should be a male dracthyr icon for male dracthyr and a female dracthyr icon for female dracthyr.

## Issue checklist

- [x] The issue occurs with the [latest version] of the addon.
- [x] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce

1. Load into WoW as a dracthyr
2. Open up TRP3 and go to Character > Profiles
3. See that "Default Profile" defaults to a question mark

**Comment by Meorawr** [comment]
Should be fixed in 2.4.2
