### ISSUE TITLE
MAKE_SURE_BROADCAST_CHANNEL_IS_LAST

### ISSUE THREAD

**Issue by Tiiara** [Total-RP/Total-RP-3#670]
## Describe the issue
Just an error message in BugSack, no idea where it came from, no apparent problems while playing. 

totalRP3 2.4.1

Give us a list of steps to reproduce the issue with.
1x Interface/AddOns/totalRP3/Core/Configuration.lua:68: Unknown config key: MAKE_SURE_BROADCAST_CHANNEL_IS_LAST
[string "=[C]"]: in function `assert'
[string "@Interface/AddOns/totalRP3/Core/Configuration.lua"]:68: in function <Interface/AddOns/totalRP3/Core/Configuration.lua:67>
[string "@Interface/AddOns/totalRP3/Core/CommunicationProtocolBroadcast.lua"]:264: in function <...Ons/totalRP3/Core/CommunicationProtocolBroadcast.lua:263>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/totalRP3/Libs/Ellyb/Tools/EventsDispatcher.lua"]:74: in function `TriggerEvent'
[string "@Interface/AddOns/totalRP3/Libs/Ellyb/Tools/GameEvents.lua"]:43: in function <...face/AddOns/totalRP3/Libs/Ellyb/Tools/GameEvents.lua:41>

**Comment by Ghostamoose** [comment]
Did you manually install the addon? I had someone else experiencing this same error, reinstalling the addon fixed it for them. Can you give that a try and see if the issue still occurs?

https://github.com/Total-RP/Total-RP-3/wiki/How-to-install-and-update-Total-RP-3

**Comment by Tiiara** [comment]
No, I use the curseforge client. I'd happily try the manual install but I tried to reproduce the error logging in now ... but it's gone.
Everything works fine again so I have no way to test if manually installing would change anything.
