### ISSUE TITLE
Wrath of the Lich King: Classic - "Scan for roleplay" feature accessed in the world map is not working properly.

### ISSUE THREAD

**Issue by WhiskeyBravoHotel** [Total-RP/Total-RP-3#673]
## Describe the issue
"Scan for roleplay" button in the game's world map is broken and is not functioning properly.

## Expected behaviour
Previously, the scan would work as expected, populating the map with a subtle animation, and small dots representing players with TRP3-enabled profiles who've opted in to broadcast their location openly.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x ] The issue occurs with the [latest version] of the addon.
- [x ] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

With TRP3 for WotLK: Classic, try and use the "scan for roleplay" feature accessed in the world map, while players with TRP3 profiles are in proximity of the scan. The error will consistently occur, even with TRP3 and it's accompanying data module being the only loaded addons.

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[TRP3_Classic_mapscan_error_ADDONS_ENABLED.txt](https://github.com/Total-RP/Total-RP-3/files/10151832/TRP3_Classic_mapscan_error_ADDONS_ENABLED.txt)
[TRP3_Classic_mapscan_error_NO_ADDONS.txt](https://github.com/Total-RP/Total-RP-3/files/10151833/TRP3_Classic_mapscan_error_NO_ADDONS.txt)

**Comment by Meorawr** [comment]
Should be fixed in 2.4.3.
