### ISSUE TITLE
attempt to index local 'tooltipData' (a nil value)

### ISSUE THREAD

**Issue by Tiiara** [Total-RP/Total-RP-3#680]
## Describe the issue
Tooltips of ppl not in range (but in group / raid) keep appearing and disappearing for split seconds. 

## Expected behaviour
simply show the TRP 3 tooltip

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [ x ] The issue occurs with the [latest version] of the addon.
- [  ] The issue occurs with Total RP 3 as the only enabled addon.
- [  ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Start game, invite someone into group not in loading distance

## Additional files
2x totalRP3/Core/UITools.lua:567: attempt to index local 'tooltipData' (a nil value)
[string "@totalRP3/Core/UITools.lua"]:567: in function <totalRP3/Core/UITools.lua:560>
[string "@totalRP3/Core/UITools.lua"]:620: in function <totalRP3/Core/UITools.lua:616>
[string "@totalRP3/Modules/TargetFrame/TargetFrame.lua"]:232: in function <totalRP3/Modules/TargetFrame/TargetFrame.lua:224>
[string "=[C]"]: in function `xpcall'
[string "@totalRP3/Libs/Ellyb/Tools/EventsDispatcher.lua"]:74: in function `TriggerEvent'
[string "@totalRP3/Libs/Ellyb/Tools/GameEvents.lua"]:43: in function <...facetotalRP3/Libs/Ellyb/Tools/GameEvents.lua:41>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

**Comment by Meorawr** [comment]
Should be fixed in 2.4.3 which we released err... about a minute after this was opened.
