### ISSUE TITLE
TipTac/TRP "merged realm" issue.

### ISSUE THREAD

**Issue by SisrenWarrior** [Total-RP/Total-RP-3#684]
Happens upon every mouseover of another player. Using TipTac and the TipTac Reborn update for it.

73x totalRP3/Libs/LibMSP/LibMSP.lua:750: Chomp.NameMergedRealm: name: expected string, got nil
[string "=[C]"]: in function `error'
[string "@totalRP3/Libs/Chomp/StringManip.lua"]:104: in function `NameMergedRealm'
[string "@totalRP3/Libs/LibMSP/LibMSP.lua"]:750: in function `Request'
[string "@TipTac/ttCore.lua"]:2171: in function `SetUnitRecordFromTip'
[string "@TipTac/ttCore.lua"]:2327: in function `?'
[string "@TipTac/libs/LibFroznFunctions-1.0-2/LibFroznFunctions-1.0.lua"]:688: in function `FireGroupEvent'
[string "@TipTac/ttCore.lua"]:1174: in function `SetCurrentDisplayParams'
[string "@TipTac/ttCore.lua"]:1086: in function <TipTac/ttCore.lua:1085>
[string "@TipTac/libs/LibFroznFunctions-1.0-2/LibFroznFunctions-1.0.lua"]:137: in function <...libs/LibFroznFunctions-1.0/LibFroznFunctions-1.0.lua:135>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:278: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:233: in function `ProcessInfo'
[string "@FrameXML/GameTooltip.lua"]:970: in function `SetWorldCursor'
[string "@FrameXML/UIParent.lua"]:1486: in function <FrameXML/UIParent.lua:1409>
[string "=[C]"]: ?

Locals:
(*temporary) = "Chomp.NameMergedRealm: name: expected string, got nil"

**Comment by Meorawr** [comment]
This is TipTac's problem - they'll be releasing an update eventually to resolve it.

**Comment by SisrenWarrior** [comment]
Wow, fast response. And understood. Thanks!

**Comment by Meorawr** [comment]
For what it's worth - there is a development version of TipTac with the fix included, if the issue is annoying enough: https://github.com/frozn/TipTac/issues/173#issuecomment-1401120495
