### ISSUE TITLE
Unable to load profiles from chat.

### ISSUE THREAD

**Issue by ElRuneburst** [Total-RP/Total-RP-3#688]
## Describe the issue
Before DF came out, I was able to right click a name in chat (usually used when I got a whisper) and open someone else's trp that way. Ever since the start of the expansion, I have been unable to do so, meaning I have to physically find whoever whispered me in-game to view their trp. Since I have a bad memory, I used this method to know who I was talking to before I responded. Now I can't do that if they messaged me and I don't remember who the in-game name is linked to. I do hope this is a bug and not an intended feature removal.

## Expected behaviour
Right click on a name in chat to be able to open a player's trp from there.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest version] of the addon.
- [x] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

1. Go to 'the whisper chat'
2. Click on 'whoever you are talking to's name'
3. See error- No option to select TRP

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by TrinitysEnd** [comment]
This has been since 2.4.0 due to bugs in Blizzard's edit mode. Until those bugs in the basic game are fixed, implementing the dropdown via right click context menus will not work without tainting every action in the game. So this was intentionally changed to not break the game for all users.

**Comment by Ghostamoose** [comment]
Trinity is correct. This won't be re-enabled until after Blizzard fixes the issues with Edit Mode.
