### ISSUE TITLE
One character's profile details carry over to every newly created character.

### ISSUE THREAD

**Issue by Gena-76** [Total-RP/Total-RP-3#692]
## Describe the issue
As the title says: One character's profile details carry over to every newly created character. 

## Expected behavior
When I open TRP on a new character, I expect to see the entry to be blank and ready for customization. Instead, it shows 4 filled-in At-A-Glance entries from another character.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x ] The issue occurs with the [latest version] of the addon.
- [x ] The issue occurs with Total RP 3 as the only enabled addon.
- [x ] The issue occurs only with other addon(s) enabled (please provide a list). Altoholic, DBM, HandyNotes, Auctionator, MasterPlan, MogIt, NPCScan, OpenAll, Rarity, Recount, TomTom, UnlimitedChatMessage.

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

Just make a new character and click the TRP icon to show the Character Page.

I am not sure what else to add. I assume this is something I have done wrong, but I cannot find it, so I am looking for help. Thanks so much for this awesome addon!

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Solanya** [comment]
You probably modified the glance slots of the default profile by right-clicking the icons when you target yourself. You should be able to clean them via the same method.

I'll see to add a safety so you can't edit glances through this target frame without creating a new profile.

**Comment by Gena-76** [comment]
Thank you so much, and I apologize for needing more of your time here - but
how do I undo this exactly? Right-click the icons of any character or the
one that the at-a-glance icons assigned to it originally?

**Comment by Solanya** [comment]
I was incorrect and it's left-click on it to edit it, but removing on any character with the default profile will do, they all share the same profile.
