### ISSUE TITLE
Elixir of Tongues notification does not function as intended

### ISSUE THREAD

**Issue by strchsr** [Total-RP/Total-RP-3#736]
When you have 3 minutes remaining on your Elixir of Tongues, there is a pop up notifying you of such, and you are given the options to "Refresh" or "Ignore". Choosing "Refresh" used to use another in your bags but it seems that this functionality is broken now.

**Comment by Meorawr** [comment]
We've never had an Elixir of Tongues notification feature in the addon. You might be thinking of Cross RP.
