### ISSUE TITLE
Odd TRP3/Plater Behavior

### ISSUE THREAD

**Issue by SisrenWarrior** [Total-RP/Total-RP-3#760]
## Describe the issue
Nameplates are getting "caught" towards the edge of the screen if they contain a title (NPC) or guild (player).

## Expected behaviour
Nameplates should not remain on screen when source is not visible.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [X] The issue occurs with the [latest version] of the addon.
- [ ] The issue occurs with Total RP 3 as the only enabled addon.
- [X] The issue occurs only with other addon(s) enabled (please provide a list).
      - Plater
      - Plater TRP3 Mod Enabled (possible culprit)

## Steps to reproduce
1)Have Plater activated with TRP3 Mod enabled AND TRP3 addon enabled
2)Run around a populated area (Valdrakken, for instance)
3) Issue occurs

## Additional files
[Screenshot](https://ibb.co/z7pRRxK)

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Ghostamoose** [comment]
I'm aware of this and currently looking into it, will try to have it fixed as soon as possible.
