### ISSUE TITLE
Nameplates display only when clicked.

### ISSUE THREAD

**Issue by RePeterCSA** [Total-RP/Total-RP-3#762]
## Describe the issue
Nameplates dissapeared, and are only displayed when clicking on another character. No settings were changed in game or in addon itself. Everything is set as per instructions. Im using Blizzard Nameplates.

## Expected behaviour
They should be visible all the time when module and setting in game is correctly selected.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest version] of the addon.
- [ ] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.
![image](https://user-images.githubusercontent.com/132558474/236158718-ca319efd-cb3b-488d-8edb-a3e5bc029ca7.png)
![image](https://user-images.githubusercontent.com/132558474/236158833-58557693-10d9-4719-9a9e-69aa64af1121.png)

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Solanya** [comment]
This is an issue introduced by Blizzard in 10.1, they will fix it themselves but in the meantime you can use the command `/run SetCVar("nameplatePlayerMaxDistance", 60)` to get them back.

**Comment by RePeterCSA** [comment]
Thank you so much!

I was wondering if it was the game update that messed it up.

czw., 4 maj 2023 o 11:24 Solanya ***@***.***> napisał(a):
