### ISSUE TITLE
ElvUI tooltip border color inconsistency

### ISSUE THREAD

**Issue by DarkLCF** [Total-RP/Total-RP-3#778]
## Describe the issue
When using skinned elvui tooltips, and have "show relationship color" enabled, the tooltip border color is by default white when you see the tooltips of other TRP3 users that you have no relationship with. Doesn't seem intended?

## Expected behaviour
The border color should not change/become white

**Comment by Raenore** [comment]
This has been resolved in #695.

No more white tooltip border for no relationship.
![image](https://github.com/Total-RP/Total-RP-3/assets/172234435/3e639265-2fcf-42fd-965b-ffc1d8bb658e)
