### ISSUE TITLE
Cannot load addon on fresh install - attempt to index field 'loc' (a nil value)

### ISSUE THREAD

**Issue by kynodoxia** [Total-RP/Total-RP-3#779]
## Describe the issue
As title. Minimal other addon interaction, disabled MRP, Plater, Prat, and Kui just to be safe.

![image](https://github.com/Total-RP/Total-RP-3/assets/102188485/da266403-340a-40ac-b926-cc4911eec640)

## Expected behaviour
The addon to work. :P More specifically, 'loc' is passing in as null, where it should be set to the locality of my game client.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest version] of the addon.
- [x] The issue occurs with Total RP 3 as the only enabled addon.
- [x] The issue occurs only with other addon(s) enabled (please provide a list). (See above, have tested with those as well.) 

![image](https://github.com/Total-RP/Total-RP-3/assets/102188485/1b7e5ff8-b9cf-4604-9521-9132ff203b36)

## Steps to reproduce

1. Log in after freshly installing TRP3 through Curseforge on a fresh install of WoW (have only been playing for a day or two after many years away).
2. It happens. Swear I'm not trying to be difficult, I do this for a living too, but... it just kind of happens.

## Additional files
See above. Thank you.
The line referenced (Locale.lua:11) is shown below. 

![image](https://github.com/Total-RP/Total-RP-3/assets/102188485/34854d47-8969-4d51-b37f-6e00845b11d7)

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Meorawr** [comment]
The only way I can see this happening is if there's other errors preventing (or perhaps indicating) that our default locale isn't loading at all. This _may_ just be a case of the CurseForge app screwing up again and not installing files correctly.

Can you confirm that enUS.lua exists in the same directory as Locale.lua and has the following near the end of the file?
https://github.com/Total-RP/Total-RP-3/blob/9e7f951280d73aac079f9432e769c0a524875f9d/totalRP3/Locales/enUS.lua#L1657

Additionally, confirm that the files loaded by Locales.xml matches the following list:
https://github.com/Total-RP/Total-RP-3/blob/9e7f951280d73aac079f9432e769c0a524875f9d/totalRP3/Locales/Locales.xml#L7-L18

**Comment by Solanya** [comment]
Try deleting the totalRP3 folders from `_retail_/Interface/AddOns` and reinstalling the addon from the client, perhaps something else is screwing up? As far as we can see, this issue shouldn't be possible if everything is properly installed.
