### ISSUE TITLE
TRP Prat Module - Dashboard Error Callback Handler and TabFrame Error

### ISSUE THREAD

**Issue by Vexonar** [Total-RP/Total-RP-3#784]
## Describe the issue
Issues stemming in chat and frames

## Expected behaviour

Errors within prat seem to stem from something in the Callback Handler stages. No longer does party get changed to [P] or other formatting. I've done clean re-installs of both TRP and Prat and cleaned out the prat saved variables

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x ] The issue occurs with the [latest version] of the addon.
- [ ] The issue occurs with Total RP 3 as the only enabled addon.
- [x ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce

Simply have TRP3 and Prat installed 

## Additional files

[TRPDashboard.txt](https://github.com/Total-RP/Total-RP-3/files/11985187/TRPDashboard.txt)

**Comment by Solanya** [comment]
We've gotten reports of that issue previously and it will be fixed in the next update coming on Tuesday.

**Comment by Vexonar** [comment]
Ah thank you so much. Apologies for not seeing it before.
