### ISSUE TITLE
TRP3 Nameplates ARE NOT working on one character but are for another character...

### ISSUE THREAD

**Issue by witchiinghour** [Total-RP/Total-RP-3#792]
I've looked through every nook and cranny for everything setting that could possibly effect my nameplates. I have Kui, I have ElvUI. I'm a roleplayer so of course I have TRP3.

TRP3 apparently integrated Kui into the main addon which is great, but I just cant seem to figure out why my nameplates just refuse to show up. Please I need help, it's been really frustrating me lately.

I can provide screenshots and images to help out with visuals. I've mocked my settings from the WORKING account over to the NOT WORKING account and nothing changed still. I just want to roleplay in peace and be able to read my fellow roleplayers ACTUAL IC names and not their forced usernames.

**Comment by Solanya** [comment]
To see RP nameplates, you need to have friendly nameplates enabled. If names above players heads are blue with no shadow (see left), you do not have friendly nameplates enabled. By default, Shift-V is the shortcut to enable them. You also need to enable "Always show nameplates" in Interface > Names to see more than your target's nameplate.

Without any addon, once enabled, friendly nameplates should look like a blue name with shadow, as well as a health bar (see middle).

If you have the TRP nameplates module enabled, nameplates will display RP name with the selected color (see right), with options to display icon, hide healthbar... able to be found in TRP Settings > Nameplates.

(Note: Your own character does not have a nameplate. Nameplates cannot be customised in instances.)

![](https://i.imgur.com/IVJ9eZa.jpg)

**Comment by witchiinghour** [comment]
You are the most amazing person in the absolute world. I had just gotten so frustrated and overwhelmed with everything I think i just started to massively overlook the simple fixes like "FriendNamePlates".

thank you so much and i really appreciate such a quick ass reply. My problem HAS BEEN FIXED! Thank you so much for helping me out. Such a tiny problem haha

I will be DEFINITELY saving this information. Thanks again Solanya! <3
