### ISSUE TITLE
Got suspended

### ISSUE THREAD

**Issue by shakoos123** [Total-RP/Total-RP-3#793]
Hey I just got suspended on WoW and all it says is "Verbal Abuse" and I don't really say anything ever in chats, so I think maybe its because I once had some dumb shit in the RP addon, but i didnt use it for ages and i deleted all the the profiles when i stopped using it, but I wanted to ask if there is somehow a way for people to still see it or something? :/

Kind regards.

**Comment by Solanya** [comment]
Profile data is logged on Blizzard servers every time the profile is received by someone, deleting profiles on your end afterwards does not hide it from them. If you had content in those profiles breaking TOS, it would be actionable.

**Comment by Solanya** [comment]
I don't know, I'm not Blizzard CS :p

**Comment by shakoos123** [comment]
Of course! I was just wondering and blizzard takes like 14 days to respond

**Comment by shakoos123** [comment]
Thank you for your help!

**Comment by shakoos123** [comment]
Again so sorry to bother you!
here is what i tried: i deleted my profile through the addon interface, i deleted the .lua files on my pc from the addon itself, i dont use the addon anymore, dont even have it installed and when i did install it just to check if its still there (the profile) it was gone on my end. is it still possible for others to see? can you please help me get rid of it if it is i have no idea what else to try and i dont want my account to keep getting banned

**Comment by Solanya** [comment]
If you don't use the addon anymore, or if you use it and deleted the profile, the data is gone and nobody will receive the profile anymore. It could linger in other players' local directory, but this won't add any more logs on Blizzard's side.
