### ISSUE TITLE
Unable to Link Companion Pet Profiles (WOTLK)

### ISSUE THREAD

**Issue by mkd172** [Total-RP/Total-RP-3#812]
Battle/companion pets are currently unable to be used on Wrath of the Lich King as you can only link a companion profile to a renamed pet. Renaming companion pets is currently not available in Wrath of the Lich King Classic.

**Comment by Meorawr** [comment]
I'll try and take a look at this for our next release - the renaming requirement stems from a few limitations in the game, but we can probably remove it for Classic.
