### ISSUE TITLE
Installed but won't show up in game

### ISSUE THREAD

**Issue by MaraWisp** [Total-RP/Total-RP-3#821]
## Describe the issue
Totalrp3 is installed but won't show up in game in my addon list. It's definitely installed.

## Expected behaviour
Give us a clear and concise description of what you expected to happen.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest version] of the addon.
- [ ] The issue occurs with Total RP 3 as the only enabled addon.
- [x] The issue occurs only with other addon(s) enabled (please provide a list). (astral keys, auctionator, bagnon, dbm, details, handynotes, leatrix, omnicd. plater. postal. prat 3.0, sexymap. tomtom, vuhdo, WA, wq tracker

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Solanya** [comment]
The addon not showing up in the list means the addon is not properly installed.
If you're using an addon client, make sure the right WoW version (and path) is selected.
If you're installing manually, make sure both folders (totalRP3 and totalRP3_Data) are placed in Interface/AddOns directly.
