### ISSUE TITLE
[Bug] Unable to Edit 'About' if Character Theme Song Returns NIL Value

### ISSUE THREAD

**Issue by illutian** [Total-RP/Total-RP-3#823]
Game Version: Classic SoD
Addon Version: Classic Era 2.6.2*
_*Addon Saved Variable Version: Classic Wrath 2.6.2_

I copied the TRP3 Saved Variable LUA from Classic Wrath to Classic SoD. Issue is the song I have is from Wrath's sound file. This is totally on me. But it does highlight a fail point. I figured what would happen is if the song didn't exist it would just be blank and I could edit it to be one that is present in the game files.

I would recommend that if 'Character Theme' returns a NIL value then a default song track is used that is present in all iterations of WoW.

EDIT: For anyone having the same issue. Edit the variable called "MU" in the Saved Variable file. I used 53455, which is 'enchantedforest_03' and should be present in Vanilla onward.

**Comment by Solanya** [comment]
Will have it fixed for next version.

**Comment by Meorawr** [comment]
> be solanya
> mark as fixed
> forget to close ticket
