### ISSUE TITLE
I've been getting a Lua error in regards to the SetAlpha for GlannceBarSlots

### ISSUE THREAD

**Issue by JSON-135** [Total-RP/Total-RP-3#827]
## Describe the issue
TRP3 throws an error when trying to use AND/OR view a particular icon called 7fx_alphamask_glow_teal_blend in glance slots. I have pasted the error in the error log down below from bugsack. You can replicate it by selecting the icon in a glance slot. Or clicking on a player using the icon in a glance slot.

Note: TRP3 also throws an error when clicking on other players that also use this icon in their glance slots.
And TRP3 throws a different error when trying to use the icon in your own Glace icon slot.

## Expected behaviour
Not really sure how to explain this one. When i click on some players profiles that are using the icon or if i try to use it myself, i recieve a error message.

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest version] of the addon.
- [ ] The issue occurs with Total RP 3 as the only enabled addon.
- [x] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

1. Go to 'Glance editor'
2. Click on 'the glance icon slot'
3. Search for '7fx_alphamask_glow_teal_blend'
4. Select and apply that icon.
5. Then TRP3 throws an error.

OR

1. Find a player using the glance icon in a glance slot
2. Click on said player using said icon
3. TRP3 throws error

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.
![image](https://github.com/Total-RP/Total-RP-3/assets/37351631/cf0a5482-0d34-4ec7-8cb7-213f64c9771d)
---

[error logs]: 

```
1x TRP3_GlanceBarSlot3:SetAlpha(): SetPortraitToTexture(): Texture is not 64x64 pixels: FileData ID 611426.

Lua Taint: totalRP3
[string "=[C]"]: in function `SetAlpha'
[string "@totalRP3/Modules/Register/Main/RegisterGlance.lua"]:619: in function <...ns/totalRP3/Modules/Register/Main/RegisterGlance.lua:605>
[string "@totalRP3/Modules/Register/Main/RegisterGlance.lua"]:684: in function <...ns/totalRP3/Modules/Register/Main/RegisterGlance.lua:668>
[string "@totalRP3/Modules/Register/Main/RegisterGlance.lua"]:810: in function <...ns/totalRP3/Modules/Register/Main/RegisterGlance.lua:810>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@totalRP3/Core/Events.lua"]:76: in function <totalRP3/Core/Events.lua:75>
[string "=[C]"]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals:
(*temporary) = TRP3_GlanceBarSlot3 {
 GenFrameX = 0
 titleText = "|TInterface\ICONS\achievement_character_nightelf_female:30:30|t Pointed ears"
 slot = "3"
 targetID = "Druidiôt-MoonGuard"
 bodyText = "|cffff9900Sly does have somewhat pointed ears.  They are normal in size, based on her human appearance, but usually are hidden by her hair."
 data = <table> {
 }
 GenFrameAnch = "ANCHOR_LEFT"
 GenFrameY = 0
 targetType = "CHARACTER"
 isCurrentMine = false
 GenFrame = TRP3_GlanceBarSlot3 {
 }
 0 = <userdata>
 glanceTab = <table> {
 }
 Tooltip = <table> {
 }
}
(*temporary) = 1
```

**Comment by JSON-135** [comment]
Just discovered it happens while having other addons enabled going to try to figure out which addon in particular

**Comment by Meorawr** [comment]
No need - it's half a bug on our end, and half a bug on Blizzard's end. Will get it fixed for the next update.

**Comment by JSON-135** [comment]
Ahh i see, thanks!
