### ISSUE TITLE
Bug TRP3 et TRP 3 extended

### ISSUE THREAD

**Issue by hotosho** [Total-RP/Total-RP-3#833]
Hello,

I have two problems with TRP3 and TRP 3 extended.

When somoene give me a card from an hostell in rollplay, created with TRP3 extended, the card is always empty or incomplete. I accept the object like i accept every objects (clic on the interrogation point and accept everything) 

my compagnons list is empty (i have more the 800 compagnons in my collection)

-i have the latest versions of every addons
-i use only DBM, TomTom and TRP as addon

i don't know where the bug come from

Thx, have a nice day
![WoWScrnShot_123023_225102](https://github.com/Total-RP/Total-RP-3/assets/155267201/7a5d79ae-72dc-4b21-b177-6cfb98a92be8)
![WoWScrnShot_123023_225115](https://github.com/Total-RP/Total-RP-3/assets/155267201/65657672-323c-4915-9275-ce3932725d6c)

**Comment by Solanya** [comment]
For the document, there are arrows at the bottom to navigate through the pages.

For the companions, I'll need screenshots to know what your issue is. The only guess I can make is that none of your companions have a custom name, which is currently a requirement to have a profile attached.
