### ISSUE TITLE
Addon loading error when playing on Mac

### ISSUE THREAD

**Issue by Taesstory** [Total-RP/Total-RP-3#837]
New wow patch for wow dropped today and my trp3 won't work AT ALL
Im unsure what to do but here's the error message.
Please fix this?
---

Message: Interface/AddOns/totalRP3/Core/Configuration.lua:67: Unknown config key: chat_name
Time: Tue Jan 16 15:58:31 2024
Count: 1
Stack: Interface/AddOns/totalRP3/Core/Configuration.lua:67: Unknown config key: chat_name
[string "=[C]"]: in function `assert'
[string "@Interface/AddOns/totalRP3/Core/Configuration.lua"]:67: in function <Interface/AddOns/totalRP3/Core/Configuration.lua:66>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/totalRP3/Modules/ChatFrame/ChatFrame.lua"]:599: in function <...face/AddOns/totalRP3/Modules/ChatFrame/ChatFrame.lua:597>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/DiceMaster/Names.lua"]:55: in function `GetTargetCharInfo'
[string "@Interface/AddOns/DiceMaster/StatInspector.lua"]:891: in function `StatInspector_OnTabChanged'
[string "@Interface/AddOns/DiceMaster/StatInspector.lua"]:489: in function `StatInspector_Update'
[string "@Interface/AddOns/DiceMaster/Inspect.lua"]:589: in function `Inspect_Open'
[string "@Interface/AddOns/DiceMaster/Events.lua"]:25: in function `?'
[string "@Interface/AddOns/DiceMaster/Events.lua"]:38: in function `?'
[string "@Interface/AddOns/BetterWardrobe/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...obe/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/BetterWardrobe/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...obe/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/BetterWardrobe/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/BetterWardrobe/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ns/BetterWardrobe/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `TargetUnit'
[string "@Interface/FrameXML/SecureTemplates.lua"]:523: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:779: in function <Interface/FrameXML/SecureTemplates.lua:764>

Locals: (*temporary) = false
(*temporary) = "Unknown config key: chat_name"

**Comment by Solanya** [comment]
Can you test with DiceMaster disabled? That error seems to imply it's trying to access a function earlier than available.

**Comment by Solanya** [comment]
Actually, can you verify that the error you've linked is the first one in the window that shows (there are arrows at the bottom to scroll through)

**Comment by Taesstory** [comment]
Message: Interface/AddOns/totalRP3/Core/Configuration.lua:67: Unknown
config key: hide_maximize_button
Time: Tue Jan 16 16:18:20 2024
Count: 1
Stack: Interface/AddOns/totalRP3/Core/Configuration.lua:67: Unknown config
key: hide_maximize_button
[string "=[C]"]: in function `assert'
[string ***@***.***/AddOns/totalRP3/Core/Configuration.lua"]:67: in
function `getValue'
[string ***@***.***/AddOns/totalRP3/UI/Main.lua"]:76: in function
<Interface/AddOns/totalRP3/UI/Main.lua:75>
[string ***@***.***/AddOns/totalRP3/UI/Main.lua"]:83: in function
`UpdateWindowStateButtons'
[string ***@***.***/AddOns/totalRP3/UI/Main.lua"]:31: in function
<Interface/AddOns/totalRP3/UI/Main.lua:30>
[string "=[C]"]: in function `Show'
[string ***@***.***/AddOns/totalRP3/Core/MainStructure.lua"]:275: in
function `openMainFrame'
[string ***@***.***/AddOns/totalRP3/Core/MainStructure.lua"]:291: in
function `switchMainFrame'
[string
***@***.***/AddOns/totalRP3/Modules/Launcher/Launcher_Actions.lua"]:12: in
function `Activate'
[string ***@***.***/AddOns/totalRP3/Modules/Launcher/Launcher.lua"]:84: in
function <...erface/AddOns/totalRP3/Modules/Launcher/Launcher.lua:72>
[string "=(tail call)"]: ?
[string
***@***.***/AddOns/DBM-Core/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua"]:170: in
function <...AddOns/DBM-Core/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:168>

Locals: (*temporary) = false
(*temporary) = "Unknown config key: hide_maximize_button"

I just dont know what to do i deleted dicemaster and it did NOTHING

**Comment by Solanya** [comment]
Are you sure this is the first error?

**Comment by Taesstory** [comment]
Yes it is
i uninstalled and reinstalled and it still hasnt worked

**Comment by Solanya** [comment]
Can you provide a screenshot with the error?

**Comment by Taesstory** [comment]
sent on discord cus it wont let me share the screenshot

**Comment by Solanya** [comment]
Issue should be resolved with 2.7.1.
