### ISSUE TITLE
[Bug][Classic Era] Lua errors whenever the UI is loaded/reloaded

### ISSUE THREAD

**Issue by SirJorb** [Total-RP/Total-RP-3#857]
## Describe the issue
In Classic Era, any time the Wow UI is loaded, these two Lua errors are produced:

`Message: Interface/AddOns/totalRP3/Modules/Register/Characters/RegisterUIMain.xml:15 Texture Texture: Unable to load atlas entry UI-RefreshButton`
`Time: Sat Mar 23 18:10:41 2024`
`Count: 1`

`Message: Interface\FrameXML\FrameXML_Vanilla.toc:1 Interface/AddOns/totalRP3/Modules/Register/Characters/RegisterUIMain.xml:15 Texture Texture: Unable to load atlas entry UI-RefreshButton`
`Time: Sat Mar 23 18:10:41 2024`
`Count: 1`

I haven't yet determined what funtionality, if any, actually breaks, but it's annoying to get the message every time I log in.

## Expected behaviour
No errors.

## Issue checklist

- [x] The issue occurs with the [latest version] of the addon.
- [X] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce

Logging in to Classic WoW.

## Additional files

![image](https://github.com/Total-RP/Total-RP-3/assets/23423782/717d890e-d173-4d1e-aab5-e5b556d0920e)
![image](https://github.com/Total-RP/Total-RP-3/assets/23423782/e47d9226-6bed-48d5-8e52-e3d252b9cd6f)

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Meorawr** [comment]
Will be fixed in the next update (#856).
