### ISSUE TITLE
Unable to see Random Trp's 

### ISSUE THREAD

**Issue by Mektalon** [Total-RP/Total-RP-3#858]
## Describe the issue
Since last update, some TRP are visible, while other are simply missing. Some players in my guild can't see any trps anymore, even after updating.

## Expected behaviour
Would expect to be able to see other player's trp as usual

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x] The issue occurs with the [latest version] of the addon.
- [x] The issue occurs with Total RP 3 as the only enabled addon.
- [ ] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

1. Go to World of Warcraft
2. Find a rp event
3. Look around 
4. Some players won't have their trp visible to you

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Solanya** [comment]
Known Blizzard issue, addon communication with players on realms connected to yours is currently broken. There is nothing we can do for this but wait for a fix.

**Comment by Meorawr** [comment]
Blizzard resolved this issue in 10.2.7.
