### ISSUE TITLE
Green Icon Instead of Normal Tooltip Icon

### ISSUE THREAD

**Issue by mrbiiz** [Total-RP/Total-RP-3#861]
## Describe the issue
In retail and prior versions I saw a tooltip with my selected char icon. Currently in WoW classic and WoTLK classic I am seeing only a green square on all characters. I have uninstalled and reinstalled the addon and it still persists. 

## Expected behaviour
Mouseover shows selected icon

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [x ] The issue occurs with the [latest version] of the addon.
- [x ] The issue occurs with Total RP 3 as the only enabled addon.
- [ x] The issue occurs only with other addon(s) enabled (please provide a list). 
          Elv Ui

![TRP](https://github.com/Total-RP/Total-RP-3/assets/166539100/d905b826-884f-41d3-a15b-2c61a871bda9)
![TRP](https://github.com/Total-RP/Total-RP-3/assets/166539100/fa93222b-cfb6-40b9-bbd2-22ee6761d140)

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by mrbiiz** [comment]
Thank you I tried searching for them in open tickets and I must have missed it! <3

**Comment by Solanya** [comment]
I don't think we had made a ticket for those, so it was fair ^^ I'll keep it open until fixed
