### ISSUE TITLE
LibRPMedia Error Cata Classicc

### ISSUE THREAD

**Issue by mrbiiz** [Total-RP/Total-RP-3#868]
## Describe the issue
When I load TRP most of the settings are missing the addon doesn't load due an error during loading sequence on Cata Classic
![TRPBug](https://github.com/Total-RP/Total-RP-3/assets/166539100/cd746b21-ac5f-4c9b-b912-a5fc7d927b5d)

## Issue checklist
Please select any applicable options from the below list.

> You can replace the "[ ]" with "[x]" for each option below to tick it.

- [ X] The issue occurs with the [latest version] of the addon.
- [ X] The issue occurs with Total RP 3 as the only enabled addon.
- [ X] The issue occurs only with other addon(s) enabled (please provide a list).

## Steps to reproduce
Give us a list of steps to reproduce the issue with.

## Additional files
Please attach any additional applicable files such as screenshots, [error logs], or [profile data files]. Files can be dragged and dropped into this report to attach them for upload.

---

[error logs]: https://www.curseforge.com/wow/addons/bugsack
[profile data files]: https://github.com/Total-RP/Total-RP-3/wiki/Saved-Variables
[latest version]: https://www.curseforge.com/wow/addons/total-rp-3/files

**Comment by Solanya** [comment]
You don't have the latest version of the addon, latest version is 2.8.1
