### ISSUE TITLE
TRPs infinitely loading, scan not working

### ISSUE THREAD

**Issue by EliHaser** [Total-RP/Total-RP-3#874]
Between yesterday and today, suddenly TRP3 can't seem to load other people's profiles, and gets stuck with the spinning arrow until WoW gives you the message that it's causing too many LUA errors. Aside of this, the map button seems mostly stuck on grey with a message saying it's being configured at the time. For those who the button works, it can't seem to retrieve people's profiles on the map.

Since there was no new version as far as I know, I'd guess this has to be related to a Blizzard change, but I report it in case the issue isn't known.

**Comment by Solanya** [comment]
`/console scriptErrors 1` and `/reload` to enable Lua errors so we know what the issue is
